// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-11-imp-1/prompts/action-05.ts

/**
 * Action 05: 優先度順に整理した朝会資料を自動生成
 * 
 * tx-11-imp-1 エージェントの Action 5
 * 提出済み日報から抽出・優先度付けされた課題を、
 * 朝会用資料として整理・フォーマットして生成する
 */

export const ACTION_05_PROMPT_VERSION = "1.0.0";

export interface Action05Input {
  prioritizedIssues: Array<{
    id: string;
    title: string;
    description: string;
    priority: "high" | "medium" | "low";
    category: string;
    reportedBy: string;
    reportedAt: string;
    relatedPastIssues?: string[];
    recommendedAction?: string;
  }>;
  unsubmittedMembers: Array<{
    memberId: string;
    memberName: string;
    lastSubmittedAt?: string;
  }>;
  reportingPeriod: {
    startDate: string;
    endDate: string;
  };
  departmentName: string;
  meetingDate: string;
  meetingTime: string;
}

export interface Action05Output {
  materialId: string;
  title: string;
  content: {
    summary: string;
    sections: Array<{
      sectionTitle: string;
      sectionType: "overview" | "high_priority" | "medium_priority" | "low_priority" | "unsubmitted" | "recommendations";
      items: Array<{
        itemId: string;
        itemTitle: string;
        itemContent: string;
        metadata?: Record<string, unknown>;
      }>;
    }>;
  };
  generatedAt: string;
  readyForMeeting: boolean;
  notificationMessage: string;
}

export interface Action05Context {
  agentId: string;
  executionId: string;
  timestamp: string;
}

/**
 * 優先度順に整理した朝会資料を自動生成するプロンプトを構築
 * 
 * @param input - Action 05 の入力データ
 * @param context - 実行コンテキスト
 * @returns 生成されたプロンプト文字列
 */
export function buildAction05Prompt(
  input: Action05Input,
  context: Action05Context
): string {
  const highPriorityIssues = input.prioritizedIssues.filter(
    (issue) => issue.priority === "high"
  );
  const mediumPriorityIssues = input.prioritizedIssues.filter(
    (issue) => issue.priority === "medium"
  );
  const lowPriorityIssues = input.prioritizedIssues.filter(
    (issue) => issue.priority === "low"
  );

  const unsubmittedCount = input.unsubmittedMembers.length;
  const totalIssuesCount = input.prioritizedIssues.length;

  const prompt = `
# 朝会資料自動生成タスク

## 実行コンテキスト
- エージェントID: ${context.agentId}
- 実行ID: ${context.executionId}
- 実行時刻: ${context.timestamp}

## 入力データ

### 報告期間
- 開始日: ${input.reportingPeriod.startDate}
- 終了日: ${input.reportingPeriod.endDate}

### 朝会情報
- 部門: ${input.departmentName}
- 開催日: ${input.meetingDate}
- 開催時刻: ${input.meetingTime}

### 優先度付け済み課題サマリー
- 高優先度: ${highPriorityIssues.length}件
- 中優先度: ${mediumPriorityIssues.length}件
- 低優先度: ${lowPriorityIssues.length}件
- 合計: ${totalIssuesCount}件

### 未提出メンバー
- 未提出者数: ${unsubmittedCount}名
${
  input.unsubmittedMembers.length > 0
    ? input.unsubmittedMembers
        .map((member) => `  - ${member.memberName} (ID: ${member.memberId})`)
        .join("\n")
    : "  なし"
}

## 高優先度課題（即座の対応が必要）
${
  highPriorityIssues.length > 0
    ? highPriorityIssues
        .map(
          (issue, idx) => `
${idx + 1}. ${issue.title}
   - ID: ${issue.id}
   - 説明: ${issue.description}
   - カテゴリ: ${issue.category}
   - 報告者: ${issue.reportedBy}
   - 報告日時: ${issue.reportedAt}
   ${issue.relatedPastIssues ? `- 関連過去課題: ${issue.relatedPastIssues.join(", ")}` : ""}
   ${issue.recommendedAction ? `- 推奨対応: ${issue.recommendedAction}` : ""}
`
        )
        .join("\n")
    : "  なし"
}

## 中優先度課題（本週中の対応を推奨）
${
  mediumPriorityIssues.length > 0
    ? mediumPriorityIssues
        .map(
          (issue, idx) => `
${idx + 1}. ${issue.title}
   - ID: ${issue.id}
   - 説明: ${issue.description}
   - カテゴリ: ${issue.category}
   - 報告者: ${issue.reportedBy}
   - 報告日時: ${issue.reportedAt}
   ${issue.relatedPastIssues ? `- 関連過去課題: ${issue.relatedPastIssues.join(", ")}` : ""}
   ${issue.recommendedAction ? `- 推奨対応: ${issue.recommendedAction}` : ""}
`
        )
        .join("\n")
    : "  なし"
}

## 低優先度課題（継続監視）
${
  lowPriorityIssues.length > 0
    ? lowPriorityIssues
        .map(
          (issue, idx) => `
${idx + 1}. ${issue.title}
   - ID: ${issue.id}
   - 説明: ${issue.description}
   - カテゴリ: ${issue.category}
   - 報告者: ${issue.reportedBy}
   - 報告日時: ${issue.reportedAt}
   ${issue.relatedPastIssues ? `- 関連過去課題: ${issue.relatedPastIssues.join(", ")}` : ""}
   ${issue.recommendedAction ? `- 推奨対応: ${issue.recommendedAction}` : ""}
`
        )
        .join("\n")
    : "  なし"
}

## タスク

以下の要件に従い、朝会用資料を自動生成してください：

### 要件
1. **資料構成**
   - タイトル: 「${input.departmentName} 朝会報告資料 - ${input.meetingDate}」
   - 概要セクション: 本日の課題総数、優先度別の内訳、未提出者情報を簡潔にまとめる
   - 高優先度課題セクション: 即座の対応が必要な課題を詳細に記載
   - 中優先度課題セクション: 本週中の対応を推奨する課題を記載
   - 低優先度課題セクション: 継続監視対象の課題を記載
   - 未提出者セクション: 未提出メンバーのリストと催促状況を記載
   - 推奨アクションセクション: 部長が朝会で指示すべき対応方針を提案

2. **フォーマット要件**
   - 各課題は ID、タイトル、説明、カテゴリ、報告者、報告日時を含める
   - 関連過去課題がある場合は「同一課題の再発」として強調表示
   - 推奨対応がある場合は「推奨アクション」として明記
   - 優先度別に視覚的に区別できるようにセクション分けする

3. **品質要件**
   - 資料は朝会開始前に部長が確認できる状態であること
   - 各課題の説明は簡潔かつ明確であること
   - 優先度判定の根拠が明確であること
   - 未提出者への催促状況が明記されていること

4. **出力形式**
   以下の JSON 形式で出力してください：
   {
     "materialId": "生成された資料の一意識別子",
     "title": "資料のタイトル",
     "content": {
       "summary": "資料全体の概要（100字程度）",
       "sections": [
         {
           "sectionTitle": "セクションのタイトル",
           "sectionType": "overview|high_priority|medium_priority|low_priority|unsubmitted|recommendations",
           "items": [
             {
               "itemId": "項目の一意識別子",
               "itemTitle": "項目のタイトル",
               "itemContent": "項目の詳細内容",
               "metadata": { "key": "value" }
             }
           ]
         }
       ]
     },
     "generatedAt": "ISO 8601 形式の生成日時",
     "readyForMeeting": true|false,
     "notificationMessage": "部長への通知メッセージ"
   }

## 実行指示

上記の要件に従い、朝会用資料を自動生成してください。
生成された資料は、部長が朝会開始前に確認できる状態で、
かつ朝会での課題共有時間を最小化できるよう、
優先度別に明確に整理されていることを確認してください。
`;

  return prompt;
}
