// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-11-imp-1/prompts/action-02.ts

/**
 * Action 02 Prompt Module for tx-11-imp-1 Agent
 * 
 * Responsibility: Generate prompt for Action 02
 * - Automated daily monitoring of report submission status
 * - Sending reminder notifications to non-submitters
 * - Extracting issues from submitted reports
 * - Searching for past similar issues and reference information
 * - Creating priority-ranked summary for morning meeting
 */

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02PromptInput {
  reportingDate: string;
  nonSubmittersList: Array<{
    memberId: string;
    memberName: string;
    lastSubmissionDate: string | null;
    reminderCount: number;
  }>;
  submittedReports: Array<{
    memberId: string;
    memberName: string;
    submissionTime: string;
    reportContent: string;
    extractedIssues: Array<{
      issueId: string;
      description: string;
      severity: "low" | "medium" | "high" | "critical";
      category: string;
    }>;
  }>;
  pastIssuesDatabase: Array<{
    issueId: string;
    description: string;
    category: string;
    firstReportedDate: string;
    occurrenceCount: number;
    resolutionStatus: "resolved" | "ongoing" | "escalated";
    relatedMemberIds: string[];
  }>;
  priorityRules: {
    severityWeights: Record<string, number>;
    categoryWeights: Record<string, number>;
    recurrenceMultiplier: number;
    escalationThreshold: number;
  };
  departmentContext: {
    departmentId: string;
    departmentName: string;
    totalMembers: number;
    managerName: string;
    managerEmail: string;
  };
}

export interface Action02PromptOutput {
  systemPrompt: string;
  userPrompt: string;
  metadata: {
    version: string;
    generatedAt: string;
    actionType: "automated_monitoring_and_summary";
    expectedOutputFormat: "json";
  };
}

export function buildAction02Prompt(input: Action02PromptInput): Action02PromptOutput {
  const systemPrompt = buildSystemPrompt();
  const userPrompt = buildUserPrompt(input);

  return {
    systemPrompt,
    userPrompt,
    metadata: {
      version: ACTION_02_PROMPT_VERSION,
      generatedAt: new Date().toISOString(),
      actionType: "automated_monitoring_and_summary",
      expectedOutputFormat: "json",
    },
  };
}

function buildSystemPrompt(): string {
  return `You are an AI agent responsible for automated daily report monitoring and analysis in a morning meeting management system.

Your role is to:
1. Monitor daily report submission status across all team members
2. Identify non-submitters and prepare reminder notifications
3. Extract issues from submitted reports using natural language processing
4. Search for past similar issues and provide reference information
5. Prioritize extracted issues based on severity, category, and recurrence patterns
6. Generate a priority-ranked summary for the manager's morning meeting preparation

You must maintain accuracy in issue extraction, fair prioritization based on defined rules, and clear communication in notifications.

Output format: Provide your analysis as a valid JSON object with the following structure:
{
  "submissionStatus": {
    "totalMembers": number,
    "submitted": number,
    "nonSubmitted": number,
    "submissionRate": number (0-100)
  },
  "reminderNotifications": [
    {
      "memberId": string,
      "memberName": string,
      "notificationMessage": string,
      "priority": "normal" | "urgent",
      "reminderCount": number
    }
  ],
  "extractedIssues": [
    {
      "issueId": string,
      "description": string,
      "reportedBy": string,
      "reportedAt": string,
      "severity": "low" | "medium" | "high" | "critical",
      "category": string,
      "relatedPastIssues": [
        {
          "pastIssueId": string,
          "similarity": number (0-100),
          "occurrenceCount": number,
          "resolutionStatus": string
        }
      ]
    }
  ],
  "prioritizedSummary": [
    {
      "rank": number,
      "issueId": string,
      "description": string,
      "severity": string,
      "priorityScore": number (0-100),
      "reportedBy": string,
      "recommendedAction": string,
      "escalationRequired": boolean,
      "relatedMembers": string[]
    }
  ],
  "managerSummary": {
    "criticalIssuesCount": number,
    "highPriorityIssuesCount": number,
    "nonSubmitterCount": number,
    "submissionRate": number,
    "keyInsights": string[],
    "recommendedFocusAreas": string[]
  }
}`;
}

function buildUserPrompt(input: Action02PromptInput): string {
  const nonSubmittersSection = formatNonSubmitters(input.nonSubmittersList);
  const submittedReportsSection = formatSubmittedReports(input.submittedReports);
  const pastIssuesSection = formatPastIssues(input.pastIssuesDatabase);
  const priorityRulesSection = formatPriorityRules(input.priorityRules);
  const departmentContextSection = formatDepartmentContext(input.departmentContext);

  return `Analyze the daily report submission status and generate a priority-ranked summary for the morning meeting.

REPORTING DATE: ${input.reportingDate}

${departmentContextSection}

${nonSubmittersSection}

${submittedReportsSection}

${pastIssuesSection}

${priorityRulesSection}

TASK:
1. Analyze the submission status and identify non-submitters
2. Generate appropriate reminder notifications for non-submitters
3. Extract and categorize issues from submitted reports
4. Match extracted issues with past similar issues to identify recurrence patterns
5. Apply priority rules to calculate priority scores for each issue
6. Generate a priority-ranked summary for the manager
7. Identify critical issues requiring immediate escalation
8. Provide key insights and recommended focus areas

Please ensure:
- Reminder notifications are professional and encouraging
- Issue extraction is accurate and complete
- Priority scoring follows the defined rules consistently
- Escalation recommendations are based on severity and recurrence
- The manager summary is concise and actionable`;
}

function formatNonSubmitters(
  nonSubmittersList: Array<{
    memberId: string;
    memberName: string;
    lastSubmissionDate: string | null;
    reminderCount: number;
  }>
): string {
  if (nonSubmittersList.length === 0) {
    return "NON-SUBMITTERS: All team members have submitted their reports.";
  }

  const formatted = nonSubmittersList
    .map(
      (member) =>
        `  - ${member.memberName} (ID: ${member.memberId}): Last submission ${member.lastSubmissionDate || "never"}, Reminders sent: ${member.reminderCount}`
    )
    .join("\n");

  return `NON-SUBMITTERS (${nonSubmittersList.length} members):
${formatted}`;
}

function formatSubmittedReports(
  submittedReports: Array<{
    memberId: string;
    memberName: string;
    submissionTime: string;
    reportContent: string;
    extractedIssues: Array<{
      issueId: string;
      description: string;
      severity: "low" | "medium" | "high" | "critical";
      category: string;
    }>;
  }>
): string {
  if (submittedReports.length === 0) {
    return "SUBMITTED REPORTS: No reports submitted yet.";
  }

  const formatted = submittedReports
    .map((report) => {
      const issuesText =
        report.extractedIssues.length > 0
          ? `\n    Issues: ${report.extractedIssues.map((i) => `${i.description} (${i.severity})`).join("; ")}`
          : "\n    Issues: None";

      return `  - ${report.memberName} (${report.submissionTime}):${issuesText}`;
    })
    .join("\n");

  return `SUBMITTED REPORTS (${submittedReports.length} members):
${formatted}`;
}

function formatPastIssues(
  pastIssuesDatabase: Array<{
    issueId: string;
    description: string;
    category: string;
    firstReportedDate: string;
    occurrenceCount: number;
    resolutionStatus: "resolved" | "ongoing" | "escalated";
    relatedMemberIds: string[];
  }>
): string {
  if (pastIssuesDatabase.length === 0) {
    return "PAST ISSUES DATABASE: Empty (first reporting period).";
  }

  const formatted = pastIssuesDatabase
    .map(
      (issue) =>
        `  - ${issue.description} (${issue.category}): Occurred ${issue.occurrenceCount} times, Status: ${issue.resolutionStatus}`
    )
    .join("\n");

  return `PAST ISSUES DATABASE (${pastIssuesDatabase.length} issues):
${formatted}`;
}

function formatPriorityRules(priorityRules: {
  severityWeights: Record<string, number>;
  categoryWeights: Record<string, number>;
  recurrenceMultiplier: number;
  escalationThreshold: number;
}): string {
  const severityWeightsText = Object.entries(priorityRules.severityWeights)
    .map(([key, value]) => `${key}: ${value}`)
    .join(", ");

  const categoryWeightsText = Object.entries(priorityRules.categoryWeights)
    .map(([key, value]) => `${key}: ${value}`)
    .join(", ");

  return `PRIORITY RULES:
  Severity Weights: ${severityWeightsText}
  Category Weights: ${categoryWeightsText}
  Recurrence Multiplier: ${priorityRules.recurrenceMultiplier}
  Escalation Threshold: ${priorityRules.escalationThreshold}`;
}

function formatDepartmentContext(departmentContext: {
  departmentId: string;
  departmentName: string;
  totalMembers: number;
  managerName: string;
  managerEmail: string;
}): string {
  return `DEPARTMENT CONTEXT:
  Department: ${departmentContext.departmentName} (ID: ${departmentContext.departmentId})
  Total Members: ${departmentContext.totalMembers}
  Manager: ${departmentContext.managerName} (${departmentContext.managerEmail})`;
}
