// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-11-imp-1/prompts/action-03.ts

/**
 * src/agents/tx-11-imp-1/prompts/action-03.ts
 * 
 * Action 3: 課題を優先度付けしてサマリーを作成する
 * 
 * Contract: tx_11_imp_1
 * Orchestrator: src/agents/tx-11-imp-1/orchestrator.ts
 * 
 * このアクションは、提出された日報から抽出された課題に対して
 * 優先度付けを実行し、部長向けの朝会用サマリーを生成する。
 */

export const ACTION_03_PROMPT_VERSION = "1.0.0";

export interface ExtractedIssue {
  id: string;
  title: string;
  description: string;
  severity: "low" | "medium" | "high" | "critical";
  category: string;
  reportedBy: string;
  reportedAt: string;
  relatedPastIssues?: string[];
}

export interface PrioritizedIssue extends ExtractedIssue {
  priority: number;
  priorityReason: string;
  recommendedAction: string;
  estimatedImpact: string;
}

export interface MorningBriefSummary {
  generatedAt: string;
  totalIssuesCount: number;
  criticalIssuesCount: number;
  highPriorityIssuesCount: number;
  prioritizedIssues: PrioritizedIssue[];
  keyHighlights: string[];
  recommendedFocusAreas: string[];
  escalationRequired: boolean;
  escalationReason?: string;
}

export interface PrioritizationContext {
  pastIssueHistory: Array<{
    issueId: string;
    title: string;
    category: string;
    resolvedAt: string;
    resolutionTime: number;
  }>;
  organizationPrioritizationRules: {
    criticalKeywords: string[];
    highPriorityCategories: string[];
    escalationThresholds: {
      recurrenceCount: number;
      impactScope: string[];
    };
  };
  currentTeamContext: {
    ongoingIssuesCount: number;
    averageResolutionTime: number;
    lastEscalationDate?: string;
  };
}

export interface Action03PromptInput {
  extractedIssues: ExtractedIssue[];
  prioritizationContext: PrioritizationContext;
  departmentHead: {
    name: string;
    email: string;
  };
  meetingScheduledAt: string;
  currentTeamContext: {
    ongoingIssuesCount: number;
    averageResolutionTime: number;
    lastEscalationDate?: string;
  };
}

export interface Action03PromptOutput {
  briefSummary: MorningBriefSummary;
  rawAnalysis: string;
  confidenceScore: number;
  requiresHumanReview: boolean;
  reviewReason?: string;
}

/**
 * buildAction03Prompt
 * 
 * 抽出された課題に対して優先度付けを実行し、
 * 部長向けの朝会用サマリーを生成するプロンプトを構築する。
 * 
 * @param input - Action 3 の入力データ
 * @returns プロンプト文字列と期待される出力形式
 */
export function buildAction03Prompt(input: Action03PromptInput): {
  systemPrompt: string;
  userPrompt: string;
  expectedOutputFormat: string;
} {
  const systemPrompt = `You are an AI assistant specialized in prioritizing issues and generating executive summaries for morning briefings.

Your role is to:
1. Analyze extracted issues from daily reports
2. Apply prioritization rules based on severity, impact, and recurrence patterns
3. Identify critical issues requiring immediate escalation
4. Generate a concise morning brief summary for the department head
5. Provide actionable recommendations

Prioritization Criteria:
- Severity: Critical > High > Medium > Low
- Recurrence: Issues reported multiple times get higher priority
- Impact Scope: Issues affecting multiple teams/systems get higher priority
- Time Sensitivity: Issues with immediate deadlines get higher priority
- Business Impact: Issues affecting revenue/customer satisfaction get higher priority

Output must be valid JSON matching the specified schema.`;

  const organizationRules = input.prioritizationContext.organizationPrioritizationRules;
  const criticalKeywords = organizationRules.criticalKeywords.join(", ");
  const highPriorityCategories = organizationRules.highPriorityCategories.join(", ");

  const userPrompt = `Please prioritize the following extracted issues and generate a morning brief summary.

EXTRACTED ISSUES:
${JSON.stringify(input.extractedIssues, null, 2)}

PRIORITIZATION CONTEXT:
- Critical Keywords: ${criticalKeywords}
- High Priority Categories: ${highPriorityCategories}
- Escalation Threshold (Recurrence): ${organizationRules.escalationThresholds.recurrenceCount} occurrences
- Current Team Context: ${input.currentTeamContext.ongoingIssuesCount} ongoing issues, avg resolution time: ${input.currentTeamContext.averageResolutionTime} hours

PAST ISSUE HISTORY (for recurrence detection):
${JSON.stringify(input.prioritizationContext.pastIssueHistory.slice(0, 10), null, 2)}

MEETING DETAILS:
- Department Head: ${input.departmentHead.name}
- Meeting Scheduled: ${input.meetingScheduledAt}

TASK:
1. Assign priority scores (1-100, where 100 is highest priority) to each issue
2. Identify any issues that should be escalated immediately
3. Detect recurring issues and flag them
4. Generate key highlights for the morning brief
5. Recommend focus areas for the meeting
6. Create a structured summary suitable for executive review

Ensure the output is actionable and concise.`;

  const expectedOutputFormat = `{
  "briefSummary": {
    "generatedAt": "ISO 8601 timestamp",
    "totalIssuesCount": number,
    "criticalIssuesCount": number,
    "highPriorityIssuesCount": number,
    "prioritizedIssues": [
      {
        "id": "string",
        "title": "string",
        "description": "string",
        "severity": "low|medium|high|critical",
        "category": "string",
        "reportedBy": "string",
        "reportedAt": "ISO 8601 timestamp",
        "relatedPastIssues": ["string"],
        "priority": number (1-100),
        "priorityReason": "string",
        "recommendedAction": "string",
        "estimatedImpact": "string"
      }
    ],
    "keyHighlights": ["string"],
    "recommendedFocusAreas": ["string"],
    "escalationRequired": boolean,
    "escalationReason": "string or null"
  },
  "rawAnalysis": "string",
  "confidenceScore": number (0-1),
  "requiresHumanReview": boolean,
  "reviewReason": "string or null"
}`;

  return {
    systemPrompt,
    userPrompt,
    expectedOutputFormat,
  };
}