// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-5-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01PromptContext {
  extractedIssues: Array<{
    id: string;
    title: string;
    description: string;
    category: string;
    reportedBy: string;
    reportedDate: string;
  }>;
  existingToolsConfig: {
    jiraEnabled: boolean;
    asanaEnabled: boolean;
    jiraProjectKey?: string;
    asanaWorkspaceId?: string;
  };
  priorityRules: {
    highPriorityKeywords: string[];
    mediumPriorityKeywords: string[];
    lowPriorityKeywords: string[];
    escalationThreshold: number;
  };
  validationRules: {
    requiredFields: string[];
    maxDescriptionLength: number;
    allowedCategories: string[];
  };
}

export interface Action01PromptResult {
  validationStatus: "valid" | "invalid" | "partial";
  validationErrors: Array<{
    issueId: string;
    field: string;
    error: string;
  }>;
  priorityAssignments: Array<{
    issueId: string;
    priority: "high" | "medium" | "low";
    score: number;
    reasoning: string;
  }>;
  categoryAssignments: Array<{
    issueId: string;
    category: string;
    confidence: number;
  }>;
  toolIntegrationPlan: Array<{
    issueId: string;
    targetTool: "jira" | "asana" | "both" | "none";
    integrationStatus: "planned" | "ready" | "blocked";
    blockers?: string[];
  }>;
  escalationCandidates: Array<{
    issueId: string;
    reason: string;
    recommendedAction: string;
  }>;
  summary: {
    totalIssues: number;
    validIssues: number;
    invalidIssues: number;
    highPriorityCount: number;
    escalationCount: number;
    readyForIntegration: number;
  };
}

export function buildAction01Prompt(
  context: Action01PromptContext
): string {
  const priorityRulesText = `
優先度判定ルール:
- 高優先度キーワード: ${context.priorityRules.highPriorityKeywords.join(", ")}
- 中優先度キーワード: ${context.priorityRules.mediumPriorityKeywords.join(", ")}
- 低優先度キーワード: ${context.priorityRules.lowPriorityKeywords.join(", ")}
- エスカレーション閾値: ${context.priorityRules.escalationThreshold}
`;

  const validationRulesText = `
検証ルール:
- 必須フィールド: ${context.validationRules.requiredFields.join(", ")}
- 説明の最大文字数: ${context.validationRules.maxDescriptionLength}
- 許可されたカテゴリ: ${context.validationRules.allowedCategories.join(", ")}
`;

  const toolsConfigText = `
既存ツール連携設定:
- Jira連携: ${context.existingToolsConfig.jiraEnabled ? `有効 (プロジェクトキー: ${context.existingToolsConfig.jiraProjectKey})` : "無効"}
- Asana連携: ${context.existingToolsConfig.asanaEnabled ? `有効 (ワークスペースID: ${context.existingToolsConfig.asanaWorkspaceId})` : "無効"}
`;

  const issuesText = context.extractedIssues
    .map(
      (issue, index) => `
課題 ${index + 1}:
- ID: ${issue.id}
- タイトル: ${issue.title}
- 説明: ${issue.description}
- カテゴリ: ${issue.category}
- 報告者: ${issue.reportedBy}
- 報告日時: ${issue.reportedDate}
`
    )
    .join("\n");

  return `あなたは朝会報告管理システムの課題検証・優先度判定エージェントです。

以下の抽出済み課題データを検証し、優先度を判定し、既存ツール連携の可否を判断してください。

${toolsConfigText}

${priorityRulesText}

${validationRulesText}

対象課題:
${issuesText}

実行すべきタスク:
1. 各課題について、必須フィールドの完全性を検証する
2. 課題の説明文から優先度キーワードを抽出し、優先度スコアを算出する
3. 課題のカテゴリが許可されたカテゴリに該当するか確認する
4. 複数カテゴリに該当する課題を特定する
5. 優先度スコアがエスカレーション閾値を超える課題を特定する
6. 各課題について、Jira/Asanaへの登録可否を判定する
7. 検証エラー、優先度判定、カテゴリ判定、ツール連携計画、エスカレーション候補をまとめる

出力形式:
JSON形式で以下の構造で返してください:
{
  "validationStatus": "valid" | "invalid" | "partial",
  "validationErrors": [
    {
      "issueId": "string",
      "field": "string",
      "error": "string"
    }
  ],
  "priorityAssignments": [
    {
      "issueId": "string",
      "priority": "high" | "medium" | "low",
      "score": number,
      "reasoning": "string"
    }
  ],
  "categoryAssignments": [
    {
      "issueId": "string",
      "category": "string",
      "confidence": number
    }
  ],
  "toolIntegrationPlan": [
    {
      "issueId": "string",
      "targetTool": "jira" | "asana" | "both" | "none",
      "integrationStatus": "planned" | "ready" | "blocked",
      "blockers": ["string"]
    }
  ],
  "escalationCandidates": [
    {
      "issueId": "string",
      "reason": "string",
      "recommendedAction": "string"
    }
  ],
  "summary": {
    "totalIssues": number,
    "validIssues": number,
    "invalidIssues": number,
    "highPriorityCount": number,
    "escalationCount": number,
    "readyForIntegration": number
  }
}`;
}
