// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/orchestrator.ts
export { runTx3Imp1Agent } from "../../logic/src/agents/tx-3-imp-1/orchestrator";
export type { Tx3Imp1AiClient } from "../../logic/src/agents/tx-3-imp-1/orchestrator";
