// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-10-imp-1/orchestrator.ts
export { runTx10Imp1Agent } from "../../logic/adoption-training-management";
export type { Tx10AdoptionTriggerInput, Tx10AdoptionExecutionResult, AdoptionScheduleDetail, TrainingExecutionStatus, InitialReportEvaluationDetail, AdoptionReadinessVerificationResult, ScheduleMilestone, ReportFeedbackItem, Tx10Imp1AiClient } from "../../logic/adoption-training-management";
