// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-9-imp-1/prompts/action-04.ts

/**
 * src/agents/tx-9-imp-1/prompts/action-04.ts
 * 
 * Action 4: 改善施策を提案する
 * 
 * 日報集約から分析報告までの自動実行エージェント（tx-9-imp-1）の
 * 第4アクション。課題分析結果に基づいて、改善施策を提案する。
 */

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptInput {
  analysisResults: {
    prioritizedIssues: Array<{
      id: string;
      title: string;
      priority: "high" | "medium" | "low";
      category: string;
      frequency: number;
      affectedMembers: string[];
      rootCause?: string;
    }>;
    recurrencePatterns: Array<{
      issueId: string;
      pattern: string;
      occurrenceCount: number;
      lastOccurrence: string;
    }>;
    productivityMetrics: {
      averageResolutionTime: number;
      issueResolutionRate: number;
      responseTime: number;
      teamCapacity: number;
    };
  };
  organizationContext: {
    departmentName: string;
    teamSize: number;
    currentProcesses: string[];
    constraints: string[];
  };
  historicalData?: {
    previousImprovementAttempts: Array<{
      initiative: string;
      result: string;
      implementationDate: string;
    }>;
    successfulMeasures: string[];
  };
}

export interface Action04PromptOutput {
  improvementProposals: Array<{
    proposalId: string;
    title: string;
    description: string;
    targetIssues: string[];
    expectedImpact: {
      resolutionTimeReduction: number;
      issueReductionPercentage: number;
      productivityImprovement: number;
    };
    implementationSteps: Array<{
      step: number;
      action: string;
      owner: string;
      timeline: string;
      resources: string[];
    }>;
    riskFactors: string[];
    successCriteria: string[];
    priority: "high" | "medium" | "low";
  }>;
  recommendedSequence: string[];
  estimatedTimeToImplement: string;
  requiredApprovals: string[];
}

export function buildAction04Prompt(input: Action04PromptInput): string {
  const systemPrompt = `You are an expert organizational improvement consultant specializing in process optimization and team productivity enhancement.

Your task is to analyze the provided issue analysis results and organizational context, then propose concrete, actionable improvement initiatives.

Guidelines:
1. Base proposals on actual issue patterns and root causes identified in the analysis
2. Consider organizational constraints and current processes
3. Learn from historical improvement attempts to avoid repeating unsuccessful approaches
4. Prioritize proposals by potential impact and implementation feasibility
5. Provide specific, measurable success criteria
6. Identify risks and mitigation strategies
7. Suggest realistic implementation timelines
8. Recommend the optimal sequence for implementing multiple proposals`;

  const userPrompt = `Analyze the following data and propose improvement initiatives:

PRIORITIZED ISSUES:
${input.analysisResults.prioritizedIssues
  .map(
    (issue) => `
- ID: ${issue.id}
  Title: ${issue.title}
  Priority: ${issue.priority}
  Category: ${issue.category}
  Frequency: ${issue.frequency} occurrences
  Affected Members: ${issue.affectedMembers.join(", ")}
  Root Cause: ${issue.rootCause || "Not identified"}
`
  )
  .join("")}

RECURRENCE PATTERNS:
${input.analysisResults.recurrencePatterns
  .map(
    (pattern) => `
- Issue: ${pattern.issueId}
  Pattern: ${pattern.pattern}
  Occurrences: ${pattern.occurrenceCount}
  Last Occurrence: ${pattern.lastOccurrence}
`
  )
  .join("")}

PRODUCTIVITY METRICS:
- Average Resolution Time: ${input.analysisResults.productivityMetrics.averageResolutionTime} hours
- Issue Resolution Rate: ${input.analysisResults.productivityMetrics.issueResolutionRate}%
- Response Time: ${input.analysisResults.productivityMetrics.responseTime} hours
- Team Capacity: ${input.analysisResults.productivityMetrics.teamCapacity}%

ORGANIZATION CONTEXT:
- Department: ${input.organizationContext.departmentName}
- Team Size: ${input.organizationContext.teamSize}
- Current Processes: ${input.organizationContext.currentProcesses.join(", ")}
- Constraints: ${input.organizationContext.constraints.join(", ")}

${
  input.historicalData
    ? `HISTORICAL CONTEXT:
Previous Improvement Attempts:
${input.historicalData.previousImprovementAttempts
  .map(
    (attempt) => `
- Initiative: ${attempt.initiative}
  Result: ${attempt.result}
  Date: ${attempt.implementationDate}
`
  )
  .join("")}

Successful Measures:
${input.historicalData.successfulMeasures.map((measure) => `- ${measure}`).join("\n")}
`
    : ""
}

Please provide:
1. 3-5 specific improvement proposals addressing the highest-priority issues
2. For each proposal:
   - Clear title and description
   - Which issues it targets
   - Expected impact metrics
   - Step-by-step implementation plan with owners and timelines
   - Risk factors and mitigation strategies
   - Success criteria
   - Priority level (high/medium/low)
3. Recommended sequence for implementation
4. Estimated total time to implement all proposals
5. Required approvals or stakeholder involvement

Format your response as a structured JSON object matching the expected output schema.`;

  return `${systemPrompt}\n\n${userPrompt}`;
}
