// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-9-imp-1/prompts/action-06.ts

/**
 * src/agents/tx-9-imp-1/prompts/action-06.ts
 * 
 * Action 6: 分析結果と改善施策をまとめた報告書を作成し部長に提示する
 * 
 * tx_9_imp_1 契約における第6アクション
 * - 指定期間の朝会報告データ集約
 * - 生産性指標の定量化・分析
 * - 課題の優先度別分類
 * - 同一課題の再発パターン検出
 * - 改善施策の提案
 * を完了した後、分析結果と施策をまとめた報告書を作成し部長に提示する
 */

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06PromptContext {
  analysisData: {
    period: {
      startDate: string;
      endDate: string;
    };
    totalReportsCollected: number;
    nonSubmitters: string[];
    productivityMetrics: {
      totalIssues: number;
      averageResolutionDays: number;
      responseSpeedScore: number;
    };
    prioritizedIssues: Array<{
      id: string;
      title: string;
      priority: "critical" | "high" | "medium" | "low";
      frequency: number;
      category: string;
    }>;
    recurrencePatterns: Array<{
      issueId: string;
      pattern: string;
      occurrences: number;
      lastOccurrence: string;
    }>;
    proposedMeasures: Array<{
      measureId: string;
      title: string;
      targetIssue: string;
      expectedImpact: string;
      implementationDifficulty: "easy" | "medium" | "hard";
      estimatedTimeframe: string;
    }>;
  };
  departmentName: string;
  reportingPeriodLabel: string;
  managerName: string;
}

export interface Action06PromptResult {
  reportContent: {
    title: string;
    executiveSummary: string;
    sections: Array<{
      sectionTitle: string;
      content: string;
      keyFindings: string[];
    }>;
    recommendations: Array<{
      rank: number;
      recommendation: string;
      rationale: string;
      priority: "critical" | "high" | "medium" | "low";
    }>;
  };
  presentationFormat: {
    format: "markdown" | "html" | "pdf";
    estimatedPages: number;
    visualizationSuggestions: string[];
  };
  nextSteps: Array<{
    step: string;
    owner: string;
    dueDate: string;
    priority: "critical" | "high" | "medium" | "low";
  }>;
  escalationItems: Array<{
    item: string;
    reason: string;
    requiredDecision: string;
  }>;
}

export function buildAction06Prompt(
  context: Action06PromptContext
): string {
  const {
    analysisData,
    departmentName,
    reportingPeriodLabel,
    managerName,
  } = context;

  const {
    period,
    totalReportsCollected,
    nonSubmitters,
    productivityMetrics,
    prioritizedIssues,
    recurrencePatterns,
    proposedMeasures,
  } = analysisData;

  const nonSubmittersList =
    nonSubmitters.length > 0
      ? nonSubmitters.join(", ")
      : "なし";

  const prioritizedIssuesText = prioritizedIssues
    .map(
      (issue) =>
        `- [${issue.priority.toUpperCase()}] ${issue.title} (カテゴリ: ${issue.category}, 発生回数: ${issue.frequency})`
    )
    .join("\n");

  const recurrencePatternsText = recurrencePatterns
    .map(
      (pattern) =>
        `- ${pattern.pattern} (発生回数: ${pattern.occurrences}, 最終発生: ${pattern.lastOccurrence})`
    )
    .join("\n");

  const proposedMeasuresText = proposedMeasures
    .map(
      (measure) =>
        `- ${measure.title} (対象課題: ${measure.targetIssue}, 難易度: ${measure.implementationDifficulty}, 想定期間: ${measure.estimatedTimeframe})`
    )
    .join("\n");

  return `あなたは朝会報告管理システムの分析エージェントです。以下の分析結果と改善施策をまとめた報告書を作成し、部長に提示してください。

【分析対象期間】
- 開始日: ${period.startDate}
- 終了日: ${period.endDate}
- 報告期間ラベル: ${reportingPeriodLabel}

【部門情報】
- 部門名: ${departmentName}
- 部長名: ${managerName}

【データ集約結果】
- 収集した報告書数: ${totalReportsCollected}
- 未提出メンバー: ${nonSubmittersList}

【生産性指標】
- 総課題件数: ${productivityMetrics.totalIssues}
- 平均解決期間: ${productivityMetrics.averageResolutionDays}日
- 対応速度スコア: ${productivityMetrics.responseSpeedScore}/100

【優先度別課題一覧】
${prioritizedIssuesText}

【再発パターン】
${recurrencePatternsText}

【提案改善施策】
${proposedMeasuresText}

以下の要件に従って報告書を作成してください：

1. **報告書構成**
   - タイトル: 「${reportingPeriodLabel} 朝会報告分析レポート - ${departmentName}」
   - エグゼクティブサマリー: 3-5行で全体の要点を記述
   - セクション構成:
     * 分析概要（期間、対象、方法論）
     * 生産性指標の分析結果
     * 優先度別課題の詳細分析
     * 再発パターンの特定と分析
     * 改善施策の提案と実行計画

2. **主要な発見事項**
   - 生産性指標の前期比較（可能な場合）
   - 課題の傾向と変化
   - 再発課題の特徴と原因推測
   - 改善の余地がある領域

3. **推奨事項**
   - 優先度付けされた改善施策（最大5件）
   - 各施策の実行理由と期待効果
   - 実装難易度と推定期間
   - 成功指標の定義

4. **次のステップ**
   - 実行すべきアクション（所有者、期限、優先度付け）
   - 部長の判断が必要な項目
   - フォローアップのタイミング

5. **エスカレーション対象**
   - 経営判断が必要な課題
   - 部門横断的な対応が必要な課題
   - 即座の対応が必要な重大課題

6. **プレゼンテーション形式**
   - 推奨フォーマット: Markdown形式で、視覚的に理解しやすい構成
   - 推定ページ数: 3-5ページ
   - グラフ・表・図表の活用提案

出力形式は以下のJSON構造で返してください：
{
  "reportContent": {
    "title": "string",
    "executiveSummary": "string",
    "sections": [
      {
        "sectionTitle": "string",
        "content": "string",
        "keyFindings": ["string"]
      }
    ],
    "recommendations": [
      {
        "rank": number,
        "recommendation": "string",
        "rationale": "string",
        "priority": "critical" | "high" | "medium" | "low"
      }
    ]
  },
  "presentationFormat": {
    "format": "markdown" | "html" | "pdf",
    "estimatedPages": number,
    "visualizationSuggestions": ["string"]
  },
  "nextSteps": [
    {
      "step": "string",
      "owner": "string",
      "dueDate": "string",
      "priority": "critical" | "high" | "medium" | "low"
    }
  ],
  "escalationItems": [
    {
      "item": "string",
      "reason": "string",
      "requiredDecision": "string"
    }
  ]
}`;
}
