// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-9-imp-1/prompts/action-02.ts

/**
 * src/agents/tx-9-imp-1/prompts/action-02.ts
 * 
 * Action 2: 生産性指標の定量化・分析
 * 
 * 指定期間の朝会報告データから生産性指標（課題件数、解決期間、対応速度）を
 * 定量化し、課題を優先度別に分類・分析するプロンプトを生成する。
 */

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02PromptContext {
  reportingPeriodStart: string;
  reportingPeriodEnd: string;
  aggregatedReportCount: number;
  totalIssueCount: number;
  unresolvedIssueCount: number;
  averageResolutionDays: number;
  departmentName: string;
  teamMemberCount: number;
}

export interface Action02PromptResult {
  version: string;
  systemPrompt: string;
  userPrompt: string;
  context: Action02PromptContext;
}

export function buildAction02Prompt(
  context: Action02PromptContext
): Action02PromptResult {
  const systemPrompt = `You are a productivity analysis AI assistant for the morning report management system.
Your role is to analyze aggregated morning report data and quantify productivity metrics.

You must:
1. Calculate productivity indicators: issue count, resolution period, response speed
2. Classify issues by priority level (Critical, High, Medium, Low)
3. Identify patterns in issue resolution
4. Detect recurring issues and their frequency
5. Provide quantitative analysis with clear metrics
6. Present findings in a structured format suitable for management review

Always maintain objectivity and base conclusions on data.
Flag any data quality issues or anomalies detected during analysis.`;

  const userPrompt = `Analyze the following aggregated morning report data for the period ${context.reportingPeriodStart} to ${context.reportingPeriodEnd}:

Department: ${context.departmentName}
Team Members: ${context.teamMemberCount}
Total Reports Aggregated: ${context.aggregatedReportCount}
Total Issues Reported: ${context.totalIssueCount}
Unresolved Issues: ${context.unresolvedIssueCount}
Average Resolution Period: ${context.averageResolutionDays} days

Please perform the following analysis:

1. **Productivity Metrics Quantification**
   - Calculate issue density (issues per report)
   - Calculate resolution rate (resolved / total)
   - Calculate average time to resolution
   - Identify response speed trends

2. **Issue Classification by Priority**
   - Categorize all issues into priority levels
   - Provide count and percentage for each level
   - Highlight critical and high-priority issues

3. **Pattern Detection**
   - Identify recurring issue patterns
   - Detect issue clusters or related issues
   - Analyze temporal patterns (when issues occur)

4. **Performance Indicators**
   - Team productivity score (0-100)
   - Issue resolution efficiency
   - Response time consistency

5. **Data Quality Assessment**
   - Flag any incomplete or anomalous data
   - Note any data inconsistencies

Provide the analysis in JSON format with the following structure:
{
  "analysisDate": "ISO8601 timestamp",
  "period": {
    "start": "${context.reportingPeriodStart}",
    "end": "${context.reportingPeriodEnd}"
  },
  "productivityMetrics": {
    "issueDensity": number,
    "resolutionRate": number,
    "averageResolutionDays": number,
    "responseSpeedScore": number
  },
  "priorityDistribution": {
    "critical": { count: number, percentage: number },
    "high": { count: number, percentage: number },
    "medium": { count: number, percentage: number },
    "low": { count: number, percentage: number }
  },
  "recurringIssues": [
    {
      "issueType": string,
      "occurrenceCount": number,
      "lastOccurrence": string,
      "priority": string
    }
  ],
  "performanceIndicators": {
    "teamProductivityScore": number,
    "resolutionEfficiency": number,
    "responseTimeConsistency": number
  },
  "dataQualityFlags": [string],
  "summary": string
}`;

  return {
    version: ACTION_02_PROMPT_VERSION,
    systemPrompt,
    userPrompt,
    context,
  };
}
