// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-9-imp-1/orchestrator.ts
export { runTx9Imp1Agent } from "../../logic/src/agents/tx-9-imp-1/orchestrator";

/**
 * tx-9-imp-1 orchestrator module
 * 日報集約から分析報告までの自動実行エージェント
 */

/**
 * AIクライアントインターフェース
 * AIエージェントが実装すべき操作を定義
 */
export interface Tx9Imp1AiClient {
  /**
   * 指定期間の日報データを集約
   */
  aggregateReportsByPeriod(
    startDate: string,
    endDate: string,
    userIds: string[],
    teamIds: string[]
  ): Promise<Array<{
    employeeId: string;
    reportDate: string;
    yesterdayWork: string;
    todayPlan: string;
    issues: string;
  }>>;

  /**
   * 生産性指標を計算
   */
  calculateProductivityMetrics(
    reports: Array<{
      employeeId: string;
      reportDate: string;
      yesterdayWork: string;
      todayPlan: string;
      issues: string;
    }>
  ): Promise<{
    issueResolutionSpeed: number;
    reportSubmissionRate: number;
    issueRecurrenceRate: number;
    teamProductivityScore: number;
  }>;

  /**
   * 日報から課題を抽出・優先度付け
   */
  extractAndRankIssuesFromReports(
    reports: Array<{
      employeeId: string;
      reportDate: string;
      yesterdayWork: string;
      todayPlan: string;
      issues: string;
    }>
  ): Promise<Array<{
    issueId: string;
    issueContent: string;
    priorityScore: number;
    priorityRank: "high" | "medium" | "low";
    colorCode: "red" | "yellow" | "green";
    occurrenceFrequency: number;
    impactDegree: number;
  }>>;

  /**
   * 日報品質を検証
   */
  validateReportQuality(
    reports: Array<{
      employeeId: string;
      reportDate: string;
      yesterdayWork: string;
      todayPlan: string;
      issues: string;
    }>
  ): Promise<{
    qualityValidationStatus: "approved" | "rejected" | "needs_review";
    completenessPercentage: number;
  }>;

  /**
   * 抽出した課題データを保存
   */
  saveExtractedIssueData(
    reportId: string,
    issues: Array<{
      issueId: string;
      issueContent: string;
      priorityScore: number;
      priorityRank: "high" | "medium" | "low";
      colorCode: "red" | "yellow" | "green";
      occurrenceFrequency: number;
      impactDegree: number;
    }>
  ): Promise<void>;

  /**
   * 部長へ確認メールを生成・送信
   */
  generateAndSendManagerConfirmationEmail(
    managerId: string,
    reportId: string,
    metrics: {
      issueResolutionSpeed: number;
      reportSubmissionRate: number;
      issueRecurrenceRate: number;
      teamProductivityScore: number;
    },
    issues: Array<{
      issueId: string;
      issueContent: string;
      priorityScore: number;
      priorityRank: "high" | "medium" | "low";
      colorCode: "red" | "yellow" | "green";
      occurrenceFrequency: number;
      impactDegree: number;
    }>,
    suggestions: Array<{
      suggestionId: string;
      relatedIssueIds: string[];
      suggestedAction: string;
      expectedImpact: string;
      implementationPriority: "immediate" | "short_term" | "medium_term" | "long_term";
    }>
  ): Promise<{
    managerNotificationSent: boolean;
  }>;
}

/**
 * 日報集約指示
 */
export interface Tx9AggregationInstruction {
  /**
   * 集約開始日（YYYY-MM-DD形式）
   */
  aggregationStartDate: string;

  /**
   * 集約終了日（YYYY-MM-DD形式）
   */
  aggregationEndDate: string;

  /**
   * 対象ユーザーID一覧
   */
  targetUserIds: string[];

  /**
   * 対象チームID一覧（オプション）
   */
  targetTeamIds?: string[];

  /**
   * 出力形式
   */
  outputFormat: "summary" | "detailed" | "executive";

  /**
   * マネージャーID
   */
  managerId: string;
}

/**
 * 分析報告結果
 */
export interface Tx9AnalysisReportResult {
  /**
   * レポートID（UUID形式）
   */
  reportId: string;

  /**
   * 集約期間
   */
  aggregationPeriod: {
    startDate: string;
    endDate: string;
  };

  /**
   * 生産性指標
   */
  productivityMetrics: {
    issueResolutionSpeed: number;
    reportSubmissionRate: number;
    issueRecurrenceRate: number;
    teamProductivityScore: number;
  };

  /**
   * 優先度付き課題一覧
   */
  prioritizedIssues: Array<{
    issueId: string;
    issueContent: string;
    priorityScore: number;
    priorityRank: "high" | "medium" | "low";
    colorCode: "red" | "yellow" | "green";
    occurrenceFrequency: number;
    impactDegree: number;
  }>;

  /**
   * 改善施策提案
   */
  improvementSuggestions: Array<{
    suggestionId: string;
    relatedIssueIds: string[];
    suggestedAction: string;
    expectedImpact: string;
    implementationPriority: "immediate" | "short_term" | "medium_term" | "long_term";
  }>;

  /**
   * 報告ステータス
   */
  reportStatus: "completed" | "pending_review" | "failed";

  /**
   * 生成タイムスタンプ
   */
  generatedAt: string;

  /**
   * マネージャー通知送信状態
   */
  managerNotificationSent: boolean;
}
