// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-06.ts

/**
 * src/agents/tx-4-imp-1/prompts/action-06.ts
 * 
 * Action 6: 優先度順に整理した朝会資料を自動生成
 * 
 * tx_4_imp_1 契約に基づき、ダッシュボード分析から課題指示までの自動実行における
 * 第6アクション（朝会資料の自動生成）のプロンプト定義モジュール
 */

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06PromptInput {
  prioritizedIssues: Array<{
    id: string;
    title: string;
    description: string;
    priority: "critical" | "high" | "medium" | "low";
    severity: number;
    urgency: number;
    category: string;
    affectedTeams: string[];
    recommendedAction: string;
    estimatedImpact: string;
  }>;
  nonSubmittedMembers: Array<{
    memberId: string;
    memberName: string;
    department: string;
    lastSubmissionDate: string | null;
  }>;
  dashboardMetrics: {
    totalIssuesDetected: number;
    criticalIssueCount: number;
    highPriorityIssueCount: number;
    averageResolutionTime: number;
    submissionRate: number;
  };
  meetingDate: string;
  meetingTime: string;
  reportingPeriod: {
    startDate: string;
    endDate: string;
  };
}

export interface Action06PromptOutput {
  materialTitle: string;
  executiveSummary: string;
  sections: Array<{
    sectionTitle: string;
    sectionNumber: number;
    content: string;
    subsections?: Array<{
      subsectionTitle: string;
      content: string;
      keyPoints: string[];
    }>;
  }>;
  criticalIssuesHighlight: Array<{
    issueId: string;
    issueTitle: string;
    immediateAction: string;
    assignedOwner: string;
    targetResolutionDate: string;
  }>;
  nonSubmittedMembersNotice: {
    count: number;
    membersList: string[];
    followUpAction: string;
  };
  metricsSnapshot: {
    totalIssuesReported: number;
    criticalCount: number;
    submissionRatePercentage: number;
    averageResolutionHours: number;
  };
  appendices: Array<{
    appendixTitle: string;
    appendixContent: string;
  }>;
  generatedAt: string;
  materialFormat: "markdown" | "html" | "pdf";
}

/**
 * buildAction06Prompt
 * 
 * 優先度順に整理した朝会資料を自動生成するためのプロンプトを構築する
 * 
 * @param input - Action06PromptInput: 優先度付けされた課題、未提出者、ダッシュボード指標
 * @returns Action06PromptOutput: 生成された朝会資料の構造化データ
 */
export function buildAction06Prompt(input: Action06PromptInput): string {
  const systemPrompt = `You are an expert business analyst and presentation designer specializing in executive morning briefing materials.

Your task is to generate a comprehensive morning meeting briefing document based on prioritized issues, dashboard metrics, and team submission status.

The document must:
1. Provide a clear executive summary highlighting critical issues requiring immediate attention
2. Organize issues by priority level (Critical → High → Medium → Low)
3. Include specific recommended actions and assigned owners for each critical issue
4. Highlight non-submitted team members and suggest follow-up actions
5. Present key metrics in an easy-to-understand format
6. Be structured for a busy executive to review in 10-15 minutes
7. Include actionable next steps and decision points

Format the output as a structured JSON object matching the Action06PromptOutput schema.`;

  const userPrompt = `Generate a morning meeting briefing document with the following data:

Prioritized Issues (${input.prioritizedIssues.length} total):
${input.prioritizedIssues
  .map(
    (issue, idx) => `
${idx + 1}. [${issue.priority.toUpperCase()}] ${issue.title}
   - Category: ${issue.category}
   - Severity Score: ${issue.severity}/10
   - Urgency Score: ${issue.urgency}/10
   - Affected Teams: ${issue.affectedTeams.join(", ")}
   - Description: ${issue.description}
   - Recommended Action: ${issue.recommendedAction}
   - Estimated Impact: ${issue.estimatedImpact}`
  )
  .join("\n")}

Non-Submitted Members (${input.nonSubmittedMembers.length} total):
${input.nonSubmittedMembers
  .map(
    (member) => `
- ${member.memberName} (${member.department})
  Last Submission: ${member.lastSubmissionDate || "Never"}`
  )
  .join("\n")}

Dashboard Metrics:
- Total Issues Detected: ${input.dashboardMetrics.totalIssuesDetected}
- Critical Issues: ${input.dashboardMetrics.criticalIssueCount}
- High Priority Issues: ${input.dashboardMetrics.highPriorityIssueCount}
- Average Resolution Time: ${input.dashboardMetrics.averageResolutionTime} hours
- Submission Rate: ${input.dashboardMetrics.submissionRate}%

Meeting Details:
- Date: ${input.meetingDate}
- Time: ${input.meetingTime}
- Reporting Period: ${input.reportingPeriod.startDate} to ${input.reportingPeriod.endDate}

Generate a professional, actionable morning briefing document that enables the executive to:
1. Quickly understand the current status
2. Identify immediate action items
3. Make informed decisions about resource allocation
4. Address team submission compliance issues
5. Plan the meeting agenda

Return the complete briefing as a structured JSON object.`;

  return `${systemPrompt}\n\n${userPrompt}`;
}

/**
 * parseAction06Response
 * 
 * AIエージェントからの応答を Action06PromptOutput に解析する
 * 
 * @param response - AIエージェントからのテキスト応答
 * @returns Action06PromptOutput: 解析された朝会資料データ
 */
export function parseAction06Response(response: string): Action06PromptOutput {
  try {
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON object found in response");
    }

    const parsed = JSON.parse(jsonMatch[0]) as Action06PromptOutput;

    return {
      materialTitle: parsed.materialTitle || "Morning Meeting Briefing",
      executiveSummary: parsed.executiveSummary || "",
      sections: Array.isArray(parsed.sections) ? parsed.sections : [],
      criticalIssuesHighlight: Array.isArray(parsed.criticalIssuesHighlight)
        ? parsed.criticalIssuesHighlight
        : [],
      nonSubmittedMembersNotice: parsed.nonSubmittedMembersNotice || {
        count: 0,
        membersList: [],
        followUpAction: "",
      },
      metricsSnapshot: parsed.metricsSnapshot || {
        totalIssuesReported: 0,
        criticalCount: 0,
        submissionRatePercentage: 0,
        averageResolutionHours: 0,
      },
      appendices: Array.isArray(parsed.appendices) ? parsed.appendices : [],
      generatedAt: parsed.generatedAt || new Date().toISOString(),
      materialFormat: parsed.materialFormat || "markdown",
    };
  } catch (error) {
    return {
      materialTitle: "Morning Meeting Briefing",
      executiveSummary: response,
      sections: [],
      criticalIssuesHighlight: [],
      nonSubmittedMembersNotice: {
        count: 0,
        membersList: [],
        followUpAction: "",
      },
      metricsSnapshot: {
        totalIssuesReported: 0,
        criticalCount: 0,
        submissionRatePercentage: 0,
        averageResolutionHours: 0,
      },
      appendices: [],
      generatedAt: new Date().toISOString(),
      materialFormat: "markdown",
    };
  }
}
