// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-7-imp-1/prompts/action-03.ts

/**
 * Action 03 Prompt Module for tx-7-imp-1 Agent
 * 
 * Contract: tx_7_imp_1
 * Title: 月次レポート生成から分析完了までの自動実行
 * 
 * This module generates prompts for Action 3:
 * ボトルネック推移を特定する
 */

export const ACTION_03_PROMPT_VERSION = "1.0.0";

export interface BottleneckAnalysisContext {
  reportingDataPeriod: {
    startDate: string;
    endDate: string;
  };
  extractedIssues: Array<{
    id: string;
    category: string;
    occurrenceDate: string;
    severity: "low" | "medium" | "high" | "critical";
    description: string;
    affectedTeams: string[];
  }>;
  historicalBottlenecks: Array<{
    bottleneckId: string;
    name: string;
    firstDetectedDate: string;
    lastOccurrenceDate: string;
    occurrenceCount: number;
    affectedProcesses: string[];
  }>;
  analysisRules: {
    bottleneckDetectionThreshold: number;
    timeWindowDays: number;
    severityWeights: Record<string, number>;
  };
}

export interface BottleneckTransitionAnalysis {
  identifiedBottlenecks: Array<{
    bottleneckId: string;
    name: string;
    detectionDate: string;
    severity: string;
    affectedProcesses: string[];
    rootCauseHypothesis: string;
    relatedIssueIds: string[];
  }>;
  bottleneckTransitions: Array<{
    fromBottleneck: string;
    toBottleneck: string;
    transitionDate: string;
    triggeringFactor: string;
    impactAssessment: string;
  }>;
  emergingPatterns: Array<{
    patternName: string;
    detectionConfidence: number;
    affectedAreas: string[];
    predictedImpact: string;
    recommendedAction: string;
  }>;
  analysisTimestamp: string;
  analysisVersion: string;
}

export function buildAction03Prompt(
  context: BottleneckAnalysisContext
): string {
  const {
    reportingDataPeriod,
    extractedIssues,
    historicalBottlenecks,
    analysisRules,
  } = context;

  const issuesByDate = extractedIssues.reduce(
    (acc, issue) => {
      const date = issue.occurrenceDate;
      if (!acc[date]) {
        acc[date] = [];
      }
      acc[date].push(issue);
      return acc;
    },
    {} as Record<string, typeof extractedIssues>
  );

  const sortedDates = Object.keys(issuesByDate).sort();

  const historicalContext = historicalBottlenecks
    .map(
      (bn) =>
        `- ${bn.name} (ID: ${bn.bottleneckId}): 初回検出 ${bn.firstDetectedDate}, 最終発生 ${bn.lastOccurrenceDate}, 発生回数 ${bn.occurrenceCount}`
    )
    .join("\n");

  const issueTimelineContext = sortedDates
    .map((date) => {
      const issuesOnDate = issuesByDate[date];
      const issueList = issuesOnDate
        .map(
          (issue) =>
            `  * [${issue.severity.toUpperCase()}] ${issue.category}: ${issue.description} (影響チーム: ${issue.affectedTeams.join(", ")})`
        )
        .join("\n");
      return `${date}:\n${issueList}`;
    })
    .join("\n\n");

  return `あなたは朝会報告管理システムの分析エージェントです。月次レポート生成プロセスの第3段階として、ボトルネック推移を特定するタスクを実行します。

【分析対象期間】
開始日: ${reportingDataPeriod.startDate}
終了日: ${reportingDataPeriod.endDate}

【分析ルール】
- ボトルネック検出閾値: ${analysisRules.bottleneckDetectionThreshold}件以上の同一カテゴリ課題
- 時間ウィンドウ: ${analysisRules.timeWindowDays}日
- 重大度ウェイト: ${JSON.stringify(analysisRules.severityWeights)}

【過去のボトルネック履歴】
${historicalContext}

【当月の課題時系列】
${issueTimelineContext}

【実行タスク】
1. 当月の課題データから、ボトルネック検出閾値を超える課題クラスタを特定してください
2. 各ボトルネックについて、以下を分析してください:
   - ボトルネックの名称と特性
   - 検出日時と重大度
   - 影響を受けるプロセス・チーム
   - 根本原因の仮説
   - 関連する課題ID
3. 過去のボトルネック履歴と比較して、以下の推移パターンを特定してください:
   - 既存ボトルネックの解消・悪化
   - 新規ボトルネックの出現
   - ボトルネック間の因果関係
4. 新規パターンや異常な推移が検出された場合は、その特性と予測される影響を記述してください
5. 各ボトルネックに対する推奨アクションを提案してください

【出力形式】
JSON形式で以下の構造で返してください:
{
  "identifiedBottlenecks": [
    {
      "bottleneckId": "string",
      "name": "string",
      "detectionDate": "YYYY-MM-DD",
      "severity": "low|medium|high|critical",
      "affectedProcesses": ["string"],
      "rootCauseHypothesis": "string",
      "relatedIssueIds": ["string"]
    }
  ],
  "bottleneckTransitions": [
    {
      "fromBottleneck": "string",
      "toBottleneck": "string",
      "transitionDate": "YYYY-MM-DD",
      "triggeringFactor": "string",
      "impactAssessment": "string"
    }
  ],
  "emergingPatterns": [
    {
      "patternName": "string",
      "detectionConfidence": 0.0-1.0,
      "affectedAreas": ["string"],
      "predictedImpact": "string",
      "recommendedAction": "string"
    }
  ],
  "analysisTimestamp": "ISO8601形式のタイムスタンプ",
  "analysisVersion": "${ACTION_03_PROMPT_VERSION}"
}

【注意事項】
- 検出信頼度が低い場合は、その旨を明記してください
- 新規パターンが検出された場合は、エスカレーション対象として明示してください
- 分析結果に矛盾や異常値がないか、自己検証してください`;
}
