// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-7-imp-1/prompts/action-01.ts

/**
 * src/agents/tx-7-imp-1/prompts/action-01.ts
 * 
 * Action 1 prompt for tx-7-imp-1 agent:
 * "月初に自動でレポート生成トリガーを確認し、蓄積報告データを抽出"
 */

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01PromptInput {
  reportingDataStartDate: string;
  reportingDataEndDate: string;
  triggerCheckTimestamp: string;
  systemStatus: {
    isOperational: boolean;
    lastSyncTime: string;
  };
}

export interface Action01PromptOutput {
  triggerConfirmed: boolean;
  triggerCheckTime: string;
  dataExtractionPeriod: {
    startDate: string;
    endDate: string;
  };
  reportingDataCount: number;
  readyForNextAction: boolean;
  errorMessages: string[];
}

export function buildAction01Prompt(input: Action01PromptInput): string {
  const lines: string[] = [
    "# Action 1: 月初レポート生成トリガー確認と蓄積報告データ抽出",
    "",
    "## 目的",
    "毎月初日にレポート生成トリガーを確認し、当月の蓄積報告データを自動抽出する",
    "",
    "## 入力情報",
    `- レポート生成対象期間開始日: ${input.reportingDataStartDate}`,
    `- レポート生成対象期間終了日: ${input.reportingDataEndDate}`,
    `- トリガー確認時刻: ${input.triggerCheckTimestamp}`,
    `- システム稼働状態: ${input.systemStatus.isOperational ? "稼働中" : "停止中"}`,
    `- 最終同期時刻: ${input.systemStatus.lastSyncTime}`,
    "",
    "## 実行手順",
    "1. 現在の日付が月初（1日）であることを確認",
    "2. レポート生成トリガーが有効化されているか確認",
    "3. 指定期間内の蓄積報告データの存在を確認",
    "4. データ抽出の準備状態を検証",
    "5. 次のアクション（レポート生成処理）への遷移可否を判定",
    "",
    "## 出力形式",
    "JSON形式で以下の情報を返却:",
    "- triggerConfirmed: トリガー確認結果（true/false）",
    "- triggerCheckTime: トリガー確認実行時刻",
    "- dataExtractionPeriod: データ抽出対象期間",
    "- reportingDataCount: 抽出対象データ件数",
    "- readyForNextAction: 次アクション実行可否",
    "- errorMessages: エラーメッセージ配列",
  ];

  return lines.join("\n");
}
