// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-8-imp-1/orchestrator.ts
export { runTx8Imp1Agent } from "../../logic/src/agents/tx-8-imp-1/orchestrator";

/**
 * tx-8-imp-1 Orchestrator - 課題検索から可視化レポート作成までの自動実行
 *
 * 朝会報告管理システムから課題データを自動抽出し、再発パターンを時系列で分析して
 * 可視化レポートを生成し、部長に提示するAIエージェントのオーケストレーター。
 */

/**
 * 時系列の課題パターンデータ
 */
export interface TimeSeriesDataPoint {
  date: string;
  count: number;
}

/**
 * 再発パターン情報
 */
export interface RecurrentPattern {
  patternId: string;
  keyword: string;
  occurrenceCount: number;
  affectedMemberCount: number;
  timeSeriesData: TimeSeriesDataPoint[];
}

/**
 * 課題パターン分析結果
 */
export interface IssuePatternAnalysisResult {
  recurrentPatterns: RecurrentPattern[];
  analysisCompletedAt: Date;
  patternCount: number;
}

/**
 * 日報データ
 */
export interface ReportData {
  reportId: string;
  employeeId: string;
  reportDate: Date;
  yesterdayWork: string;
  todayPlan: string;
  issues: string;
}

/**
 * 集約済み日報データセット
 */
export interface AggregatedReportsResult {
  totalReportCount: number;
  reports: ReportData[];
}

/**
 * マネージャー確認メール送信結果
 */
export interface ManagerConfirmationEmailResult {
  emailSent: boolean;
  notificationTargetUserId: string;
  sentAt: Date;
}

/**
 * 可視化レポート生成結果
 */
export interface VisualizationReportResult {
  reportId: string;
  reportUrl: string;
}

/**
 * 課題パターンサマリー
 */
export interface IssuePatternSummary {
  totalIssuesAnalyzed: number;
  recurrentIssueCount: number;
  bottleneckProgressionDetected: boolean;
}

/**
 * オーケストレーション実行結果
 */
export interface Tx8Imp1ExecutionResult {
  executionStatus: 'success' | 'failure';
  visualizationReportId?: string;
  issuePatternSummary?: IssuePatternSummary;
  managerNotificationSent: boolean;
  errorMessage?: string;
}

/**
 * Tx8Imp1 AIクライアント インターフェース
 *
 * 朝会報告管理システムから課題データを検索・抽出し、再発パターンを分析して
 * 可視化レポートを生成するAIエージェントが実装すべきメソッドを定義する。
 */
export interface Tx8Imp1AiClient {
  /**
   * 指定期間の日報データを集約する
   *
   * @param startDate 分析開始日（YYYY-MM-DD形式）
   * @param endDate 分析終了日（YYYY-MM-DD形式）
   * @param targetTeamIds 対象チームID配列（undefined の場合は全チーム）
   * @returns 集約済み日報データセット
   */
  aggregateReportsByPeriod(
    startDate: string,
    endDate: string,
    targetTeamIds?: string[],
  ): Promise<AggregatedReportsResult>;

  /**
   * 指定期間の課題再発パターンを時系列で分析する
   *
   * @param reports 分析対象の日報データ配列
   * @param startDate 分析開始日（YYYY-MM-DD形式）
   * @param endDate 分析終了日（YYYY-MM-DD形式）
   * @returns 課題パターン分析結果
   */
  analyzeIssuePatternsByTimeRange(
    reports: ReportData[],
    startDate: string,
    endDate: string,
  ): Promise<IssuePatternAnalysisResult>;

  /**
   * 可視化レポートを生成する
   *
   * @param patterns 再発パターン配列
   * @param analysisStartDate 分析開始日
   * @param analysisEndDate 分析終了日
   * @returns 可視化レポート生成結果
   */
  generateVisualizationReport(
    patterns: RecurrentPattern[],
    analysisStartDate: string,
    analysisEndDate: string,
  ): Promise<VisualizationReportResult>;

  /**
   * マネージャーに確認メールを送信する
   *
   * @param managerUserId マネージャーのユーザーID
   * @param reportSummary レポートサマリー情報
   * @returns メール送信結果
   */
  generateAndSendManagerConfirmationEmail(
    managerUserId: string,
    reportSummary: IssuePatternSummary,
  ): Promise<ManagerConfirmationEmailResult>;
}
