// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: src/agents/tx-5-imp-1/orchestrator
// 関数: runTx5Imp1Agent

export interface Tx5Imp1AiClient {
    extractKeywords(text: string): Promise<string[]>;
    assessImpactScore(keywords: string[]): Promise<number>;
    classifyIssueSeverity(text: string): Promise<'high' | 'medium' | 'low'>;
}
export interface ExtractedIssue {
    id: string;
    keyword: string;
    frequency: number;
    impactScore: number;
    priorityScore: number;
    priorityLevel: 'high' | 'medium' | 'low';
    affectedMembers: string[];
}
export interface ValidationResult {
    isValid: boolean;
    sentRecordCount: number;
    discrepancies: Array<{
        type: string;
        expected?: number;
        actual?: number;
        field?: string;
        recordId?: string;
    }>;
    requiresRetry: boolean;
    notificationMessage: string;
}
export interface IntegrationResult {
    sentRecordCount: number;
    statusCode: number;
    retryable: boolean;
    sentRecords: Array<{
        id: string;
        [key: string]: any;
    }>;
}
export interface ToolIntegrationConfig {
    toolType: 'jira' | 'asana';
    apiKey: string;
    endpoint: string;
    timeoutMs: number;
}


/* AIVIC_FUNCTION_BUNDLE_START owner=runTx5Imp1Agent exports=runTx5Imp1Agent */
const __aivicBundle_1_runTx5Imp1Agent = (() => {
  async function runTx5Imp1Agent(
    input: {
      extractedIssues: Array<{
        id: string;
        title: string;
        category: string;
        priority: number;
        frequency: number;
      }>;
      targetToolType: 'jira' | 'asana';
      toolApiResponse: Array<{
        issueId: string;
        externalId?: string;
        status: 'success' | 'failed';
        errorMessage?: string;
      }>;
      expectedIssueCount: number;
      toolConnectionConfig: ToolIntegrationConfig;
      currentDateTime: Date;
      maxRetries: number;
      retryDelayMs: number;
    },
    aiClient: Tx5Imp1AiClient
  ): Promise<{
    integrationSuccess: boolean;
    successCount: number;
    failureCount: number;
    duplicateCount: number;
    missingCount: number;
    validationStatus: 'passed' | 'failed' | 'partial';
    details: Array<{
      issueId: string;
      externalId?: string;
      result: 'success' | 'duplicate' | 'missing' | 'failed';
      reason?: string;
    }>;
    shouldRetry: boolean;
    nextRetryDelayMs: number;
    notificationRequired: boolean;
    notificationMessage: string;
    failureReason: string;
  }> {
    if (input["targetToolType"] === undefined || input["targetToolType"] === null) { throw new Error("targetToolType is required"); }
    if (input["expectedIssueCount"] === undefined || input["expectedIssueCount"] === null) { throw new Error("expectedIssueCount is required"); }
    if (input["toolConnectionConfig"] === undefined || input["toolConnectionConfig"] === null) { throw new Error("toolConnectionConfig is required"); }
    if (input["currentDateTime"] === undefined || input["currentDateTime"] === null) { throw new Error("currentDateTime is required"); }
    if (aiClient === undefined || aiClient === null) { throw new Error("aiClient is required"); }
    let successCount = 0;
    let failureCount = 0;
    let duplicateCount = 0;
    let missingCount = 0;
    let firstFailureReason = '';
    const details: Array<{
      issueId: string;
      externalId?: string;
      result: 'success' | 'duplicate' | 'missing' | 'failed';
      reason?: string;
    }> = [];
  
    const responseMap = new Map(
      input.toolApiResponse.map((r) => [r.issueId, r])
    );
  
    for (const issue of input.extractedIssues) {
      const response = responseMap.get(issue.id);
  
      if (!response) {
        missingCount++;
        details.push({
          issueId: issue.id,
          result: 'missing',
          reason: 'No response from tool API',
        });
      } else if (response.status === 'success') {
        successCount++;
        details.push({
          issueId: issue.id,
          externalId: response.externalId,
          result: 'success',
        });
      } else if (response.status === 'failed') {
        const errorMsg = response.errorMessage || 'unknown error';
  
        if (errorMsg === 'duplicate') {
          duplicateCount++;
          details.push({
            issueId: issue.id,
            result: 'duplicate',
            reason: errorMsg,
          });
        } else {
          failureCount++;
          if (!firstFailureReason) {
            firstFailureReason = errorMsg;
          }
          details.push({
            issueId: issue.id,
            result: 'failed',
            reason: errorMsg,
          });
        }
      }
    }
  
    const integrationSuccess =
      failureCount === 0 && missingCount === 0 && duplicateCount === 0;
  
    let validationStatus: 'passed' | 'failed' | 'partial' = 'passed';
    if (failureCount > 0 || missingCount > 0) {
      validationStatus = 'failed';
    } else if (duplicateCount > 0) {
      validationStatus = 'partial';
    }
  
    const shouldRetry = failureCount > 0 && failureCount <= input.maxRetries;
    const nextRetryDelayMs = shouldRetry ? input.retryDelayMs : 0;
  
    const notificationRequired =
      duplicateCount > 0 || (failureCount > 0 && !shouldRetry);
  
    let notificationMessage = '';
    if (duplicateCount > 0) {
      notificationMessage = `課題データの既存ツール連携でエラーが発生しました。duplicate を確認してください。`;
    } else if (failureCount > 0 && !shouldRetry) {
      notificationMessage = `課題データの既存ツール連携でエラーが発生しました。${firstFailureReason} を確認してください。`;
    }
  
    return {
      integrationSuccess,
      successCount,
      failureCount,
      duplicateCount,
      missingCount,
      validationStatus,
      details,
      shouldRetry,
      nextRetryDelayMs,
      notificationRequired,
      notificationMessage,
      failureReason: firstFailureReason,
    };
  }
  return { runTx5Imp1Agent };
})();
export const runTx5Imp1Agent = __aivicBundle_1_runTx5Imp1Agent.runTx5Imp1Agent;
/* AIVIC_FUNCTION_BUNDLE_END owner=runTx5Imp1Agent */
