// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-04.ts

/**
 * Action 04 Prompt Module for tx-3-imp-1 Agent
 * 
 * Contract: tx_3_imp_1
 * Title: 日報集約から優先度別課題一覧提示までの自動判定・配信
 * 
 * Action 4: 優先度別に整理した課題一覧を生成する
 */

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface AggregatedReport {
  reportId: string;
  collectionDate: string;
  totalReports: number;
  extractedIssues: ExtractedIssue[];
}

export interface ExtractedIssue {
  issueId: string;
  title: string;
  description: string;
  category: string;
  impactScope: string;
  urgency: string;
  riskOfRecurrence: string;
  reportedBy: string;
  reportDate: string;
}

export interface PrioritizedIssue extends ExtractedIssue {
  priorityScore: number;
  priorityLevel: "critical" | "high" | "medium" | "low";
  recommendedAction: string;
  estimatedResolutionTime: string;
}

export interface PrioritizedIssueList {
  generatedAt: string;
  totalIssues: number;
  criticalIssues: PrioritizedIssue[];
  highIssues: PrioritizedIssue[];
  mediumIssues: PrioritizedIssue[];
  lowIssues: PrioritizedIssue[];
  summary: string;
}

export interface PriorityRules {
  criticalThreshold: number;
  highThreshold: number;
  mediumThreshold: number;
  impactWeights: {
    companyWide: number;
    multiDepartment: number;
    singleDepartment: number;
    individual: number;
  };
  urgencyWeights: {
    immediate: number;
    today: number;
    thisWeek: number;
    thisMonth: number;
  };
  recurrenceWeights: {
    highRisk: number;
    mediumRisk: number;
    lowRisk: number;
  };
}

export interface PrioritizationContext {
  aggregatedReport: AggregatedReport;
  priorityRules: PriorityRules;
  historicalIssues: ExtractedIssue[];
  departmentContext: string;
}

export function buildAction04Prompt(context: PrioritizationContext): string {
  const {
    aggregatedReport,
    priorityRules,
    historicalIssues,
    departmentContext,
  } = context;

  const historicalIssuesSummary = historicalIssues
    .slice(0, 5)
    .map(
      (issue) =>
        `- ${issue.title} (${issue.category}, reported on ${issue.reportDate})`
    )
    .join("\n");

  const extractedIssuesSummary = aggregatedReport.extractedIssues
    .map(
      (issue) =>
        `- ID: ${issue.issueId}\n` +
        `  Title: ${issue.title}\n` +
        `  Category: ${issue.category}\n` +
        `  Impact Scope: ${issue.impactScope}\n` +
        `  Urgency: ${issue.urgency}\n` +
        `  Risk of Recurrence: ${issue.riskOfRecurrence}\n` +
        `  Reported by: ${issue.reportedBy} on ${issue.reportDate}`
    )
    .join("\n\n");

  const prompt = `You are an AI assistant responsible for prioritizing extracted issues from aggregated daily reports.

## Context
Department: ${departmentContext}
Report Collection Date: ${aggregatedReport.collectionDate}
Total Reports Collected: ${aggregatedReport.totalReports}
Total Issues Extracted: ${aggregatedReport.extractedIssues.length}

## Extracted Issues
${extractedIssuesSummary}

## Priority Scoring Rules
- Critical Threshold: ${priorityRules.criticalThreshold}
- High Threshold: ${priorityRules.highThreshold}
- Medium Threshold: ${priorityRules.mediumThreshold}

Impact Scope Weights:
- Company-wide: ${priorityRules.impactWeights.companyWide}
- Multi-department: ${priorityRules.impactWeights.multiDepartment}
- Single department: ${priorityRules.impactWeights.singleDepartment}
- Individual: ${priorityRules.impactWeights.individual}

Urgency Weights:
- Immediate: ${priorityRules.urgencyWeights.immediate}
- Today: ${priorityRules.urgencyWeights.today}
- This week: ${priorityRules.urgencyWeights.thisWeek}
- This month: ${priorityRules.urgencyWeights.thisMonth}

Recurrence Risk Weights:
- High risk: ${priorityRules.recurrenceWeights.highRisk}
- Medium risk: ${priorityRules.recurrenceWeights.mediumRisk}
- Low risk: ${priorityRules.recurrenceWeights.lowRisk}

## Historical Context (Recent Similar Issues)
${historicalIssuesSummary || "No recent similar issues found."}

## Task
For each extracted issue, perform the following:

1. Calculate a priority score (0-100) based on:
   - Impact scope weight
   - Urgency weight
   - Recurrence risk weight
   - Historical recurrence pattern (if applicable)

2. Assign a priority level:
   - Critical: score >= ${priorityRules.criticalThreshold}
   - High: score >= ${priorityRules.highThreshold}
   - Medium: score >= ${priorityRules.mediumThreshold}
   - Low: score < ${priorityRules.mediumThreshold}

3. Generate a recommended action for each issue based on its priority level and nature

4. Estimate resolution time based on complexity and priority

5. Create a summary statement explaining the overall issue landscape

## Output Format
Return a JSON object with the following structure:
{
  "generatedAt": "ISO 8601 timestamp",
  "totalIssues": number,
  "criticalIssues": [
    {
      "issueId": string,
      "title": string,
      "description": string,
      "category": string,
      "impactScope": string,
      "urgency": string,
      "riskOfRecurrence": string,
      "reportedBy": string,
      "reportDate": string,
      "priorityScore": number,
      "priorityLevel": "critical",
      "recommendedAction": string,
      "estimatedResolutionTime": string
    }
  ],
  "highIssues": [...],
  "mediumIssues": [...],
  "lowIssues": [...],
  "summary": "Executive summary of the issue landscape and key recommendations"
}

Ensure the output is valid JSON and can be parsed directly.`;

  return prompt;
}
