// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-05.ts

/**
 * src/agents/tx-3-imp-1/prompts/action-05.ts
 * 
 * Action 5: 優先度別課題一覧メール送信
 * 集約済み日報から抽出・優先度付けされた課題を、
 * 部長宛にメール送信するためのプロンプト生成モジュール
 */

export const ACTION_05_PROMPT_VERSION = "1.0.0";

export interface Action05PromptInput {
  prioritizedIssues: PrioritizedIssue[];
  recipientEmail: string;
  recipientName: string;
  reportDate: string;
  organizationName?: string;
}

export interface PrioritizedIssue {
  id: string;
  title: string;
  description: string;
  priority: "critical" | "high" | "medium" | "low";
  impactScope: string;
  urgency: string;
  riskOfRecurrence: string;
  reportedBy?: string;
  reportedDate?: string;
  suggestedAction?: string;
}

export interface Action05PromptOutput {
  emailSubject: string;
  emailBody: string;
  htmlContent: string;
  recipientEmail: string;
  sendTimestamp: string;
  issueCount: number;
  priorityCounts: {
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
}

/**
 * buildAction05Prompt
 * 
 * 優先度別課題一覧をメール形式で生成するプロンプトを構築
 * 
 * @param input - Action05PromptInput
 * @returns Action05PromptOutput
 */
export function buildAction05Prompt(input: Action05PromptInput): Action05PromptOutput {
  const {
    prioritizedIssues,
    recipientEmail,
    recipientName,
    reportDate,
    organizationName = "組織",
  } = input;

  // 優先度別にカウント
  const priorityCounts = {
    critical: prioritizedIssues.filter((i) => i.priority === "critical").length,
    high: prioritizedIssues.filter((i) => i.priority === "high").length,
    medium: prioritizedIssues.filter((i) => i.priority === "medium").length,
    low: prioritizedIssues.filter((i) => i.priority === "low").length,
  };

  // メール件名の生成
  const emailSubject = `【朝会報告】優先度別課題一覧 - ${reportDate}`;

  // テキスト形式のメール本文
  const emailBody = generatePlainTextEmail(
    recipientName,
    reportDate,
    organizationName,
    prioritizedIssues,
    priorityCounts
  );

  // HTML形式のメール本文
  const htmlContent = generateHtmlEmail(
    recipientName,
    reportDate,
    organizationName,
    prioritizedIssues,
    priorityCounts
  );

  const sendTimestamp = new Date().toISOString();

  return {
    emailSubject,
    emailBody,
    htmlContent,
    recipientEmail,
    sendTimestamp,
    issueCount: prioritizedIssues.length,
    priorityCounts,
  };
}

/**
 * generatePlainTextEmail
 * プレーンテキスト形式のメール本文を生成
 */
function generatePlainTextEmail(
  recipientName: string,
  reportDate: string,
  organizationName: string,
  issues: PrioritizedIssue[],
  counts: Record<string, number>
): string {
  let body = `${recipientName} 様\n\n`;
  body += `${organizationName}の朝会報告システムより、優先度別課題一覧をお知らせします。\n\n`;
  body += `【報告日】${reportDate}\n`;
  body += `【課題総数】${issues.length}件\n`;
  body += `  - 緊急（Critical）: ${counts.critical}件\n`;
  body += `  - 高（High）: ${counts.high}件\n`;
  body += `  - 中（Medium）: ${counts.medium}件\n`;
  body += `  - 低（Low）: ${counts.low}件\n\n`;

  // 優先度順にソート
  const sortedIssues = [...issues].sort((a, b) => {
    const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });

  body += "【課題一覧】\n";
  body += "=".repeat(60) + "\n\n";

  sortedIssues.forEach((issue, index) => {
    body += `${index + 1}. [${issue.priority.toUpperCase()}] ${issue.title}\n`;
    body += `   ID: ${issue.id}\n`;
    body += `   説明: ${issue.description}\n`;
    body += `   影響範囲: ${issue.impactScope}\n`;
    body += `   緊急度: ${issue.urgency}\n`;
    body += `   再発リスク: ${issue.riskOfRecurrence}\n`;
    if (issue.reportedBy) {
      body += `   報告者: ${issue.reportedBy}\n`;
    }
    if (issue.reportedDate) {
      body += `   報告日時: ${issue.reportedDate}\n`;
    }
    if (issue.suggestedAction) {
      body += `   推奨対応: ${issue.suggestedAction}\n`;
    }
    body += "\n";
  });

  body += "=".repeat(60) + "\n\n";
  body += "本メールは自動生成されています。\n";
  body += "ご不明な点はシステム管理者までお問い合わせください。\n";

  return body;
}

/**
 * generateHtmlEmail
 * HTML形式のメール本文を生成
 */
function generateHtmlEmail(
  recipientName: string,
  reportDate: string,
  organizationName: string,
  issues: PrioritizedIssue[],
  counts: Record<string, number>
): string {
  const priorityColors: Record<string, string> = {
    critical: "#d32f2f",
    high: "#f57c00",
    medium: "#fbc02d",
    low: "#388e3c",
  };

  const priorityLabels: Record<string, string> = {
    critical: "緊急",
    high: "高",
    medium: "中",
    low: "低",
  };

  // 優先度順にソート
  const sortedIssues = [...issues].sort((a, b) => {
    const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });

  let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; color: #333; }
    .container { max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { background-color: #f5f5f5; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
    .summary { display: flex; gap: 20px; margin-bottom: 20px; }
    .summary-item { flex: 1; padding: 10px; border-left: 4px solid #ccc; background-color: #fafafa; }
    .summary-item.critical { border-left-color: #d32f2f; }
    .summary-item.high { border-left-color: #f57c00; }
    .summary-item.medium { border-left-color: #fbc02d; }
    .summary-item.low { border-left-color: #388e3c; }
    .issue { margin-bottom: 20px; border-left: 4px solid #ccc; padding: 15px; background-color: #fafafa; }
    .issue.critical { border-left-color: #d32f2f; }
    .issue.high { border-left-color: #f57c00; }
    .issue.medium { border-left-color: #fbc02d; }
    .issue.low { border-left-color: #388e3c; }
    .priority-badge { display: inline-block; padding: 4px 8px; border-radius: 3px; color: white; font-weight: bold; font-size: 12px; }
    .issue-title { font-size: 16px; font-weight: bold; margin: 10px 0; }
    .issue-field { margin: 8px 0; }
    .issue-label { font-weight: bold; color: #666; }
    .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <p>${recipientName} 様</p>
      <p>${organizationName}の朝会報告システムより、優先度別課題一覧をお知らせします。</p>
    </div>

    <div style="margin-bottom: 20px;">
      <p><strong>【報告日】</strong>${reportDate}</p>
      <p><strong>【課題総数】</strong>${issues.length}件</p>
    </div>

    <div class="summary">
      <div class="summary-item critical">
        <div style="font-size: 24px; font-weight: bold; color: #d32f2f;">${counts.critical}</div>
        <div>緊急（Critical）</div>
      </div>
      <div class="summary-item high">
        <div style="font-size: 24px; font-weight: bold; color: #f57c00;">${counts.high}</div>
        <div>高（High）</div>
      </div>
      <div class="summary-item medium">
        <div style="font-size: 24px; font-weight: bold; color: #fbc02d;">${counts.medium}</div>
        <div>中（Medium）</div>
      </div>
      <div class="summary-item low">
        <div style="font-size: 24px; font-weight: bold; color: #388e3c;">${counts.low}</div>
        <div>低（Low）</div>
      </div>
    </div>

    <h2>【課題一覧】</h2>
`;

  sortedIssues.forEach((issue, index) => {
    const badgeColor = priorityColors[issue.priority];
    const priorityLabel = priorityLabels[issue.priority];

    html += `
    <div class="issue ${issue.priority}">
      <div style="display: flex; align-items: center; gap: 10px;">
        <span class="priority-badge" style="background-color: ${badgeColor};">${priorityLabel}</span>
        <span class="issue-title">${index + 1}. ${escapeHtml(issue.title)}</span>
      </div>
      <div class="issue-field">
        <span class="issue-label">ID:</span> ${escapeHtml(issue.id)}
      </div>
      <div class="issue-field">
        <span class="issue-label">説明:</span> ${escapeHtml(issue.description)}
      </div>
      <div class="issue-field">
        <span class="issue-label">影響範囲:</span> ${escapeHtml(issue.impactScope)}
      </div>
      <div class="issue-field">
        <span class="issue-label">緊急度:</span> ${escapeHtml(issue.urgency)}
      </div>
      <div class="issue-field">
        <span class="issue-label">再発リスク:</span> ${escapeHtml(issue.riskOfRecurrence)}
      </div>
`;

    if (issue.reportedBy) {
      html += `
      <div class="issue-field">
        <span class="issue-label">報告者:</span> ${escapeHtml(issue.reportedBy)}
      </div>
`;
    }

    if (issue.reportedDate) {
      html += `
      <div class="issue-field">
        <span class="issue-label">報告日時:</span> ${escapeHtml(issue.reportedDate)}
      </div>
`;
    }

    if (issue.suggestedAction) {
      html += `
      <div class="issue-field">
        <span class="issue-label">推奨対応:</span> ${escapeHtml(issue.suggestedAction)}
      </div>
`;
    }

    html += `
    </div>
`;
  });

  html += `
    <div class="footer">
      <p>本メールは自動生成されています。</p>
      <p>ご不明な点はシステム管理者までお問い合わせください。</p>
    </div>
  </div>
</body>
</html>
`;

  return html;
}

/**
 * escapeHtml
 * HTML特殊文字をエスケープ
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (char) => map[char]);
}
