import { getReportSubmissionDeadline } from "./report-submission-management";
// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: dashboard-presentation
// 関数: prepareDashboardData, formatIssueListWithColorCoding, aggregateSubmissionStatusSummary, buildUnsubmittedMembersList, structureIssueKeywordRankingData, enrichDashboardWithRealtimeUpdates

export interface DashboardDisplayData {
    submissionStatusSummary: SubmissionStatusSummary;
    unsubmittedMembers: UnsubmittedMemberInfo[];
    prioritizedIssueList: PrioritizedIssueDisplay[];
    issueKeywordRanking: IssueKeywordRankingItem[];
    lastUpdatedAt: Date;
}
export interface DashboardDataPrepareInput {
    teamId: string;
    targetDate: Date;
    requestingUserId: string;
    includeHistoricalTrend?: boolean;
}
export interface SubmissionStatusSummary {
  [key: string]: any;
}
export interface UnsubmittedMemberInfo {
    memberId: string;
    memberName: string;
    department?: string;
    colorCode?: string;
}
export interface PrioritizedIssueDisplay {
    issueId: string;
    issueContent: string;
    priorityScore: number;
    colorCode: string;
    impactLevel: string;
    reporterName: string;
    content?: string;
    frequency?: number;
    reporterCount?: number;
}
export interface IssueKeywordRankingItem {
    keyword: string;
    frequency: number;
    percentageOfTotal: number;
    rank?: number;
    averageImpactScore?: number;
    colorCode?: string;
    occurrenceRate?: number;
}
export interface SubmissionStatusAggregationInput {
    teamId: string;
    reportDate: string;
    requestUserId: string;
}
export interface UnsubmittedMember {
    memberId: string;
    memberName: string;
}
export interface IssueListForColorCodingInput {
    issues: Array<{
        issueId: string;
        issueContent: string;
        priorityScore: number;
        impactDegree: number;
        frequency: number;
    }>;
    highlightThresholdScore?: number;
    colorScheme?: 'standard' | 'accessible';
}
export interface ColorCodedIssueListOutput {
    coloredIssues: Array<{
        issueId: string;
        issueContent: string;
        priorityScore: number;
        colorCode: string;
        priorityRank: 'high' | 'medium' | 'low';
        isHighlighted: boolean;
    }>;
    colorDistribution: {
        red: number;
        yellow: number;
        green: number;
    };
    highlightedIssueCount: number;
}
export interface IssueKeywordRankingInput {
    reportDataset: Array<{
        reportId: string;
        keywords: string[];
        frequency: number;
        impactScore: number;
    }>;
    aggregationPeriodStart: Date;
    aggregationPeriodEnd: Date;
    minFrequencyThreshold?: number;
    maxRankingItems?: number;
}
export interface IssueKeywordRankingOutput {
    rankedKeywords: Array<{
        rank: number;
        keyword: string;
        frequency: number;
        averageImpactScore: number;
        colorCode: string;
        percentageOfTotal: number;
    }>;
    totalKeywordCount: number;
    aggregationPeriod: {
        startDate: string;
        endDate: string;
    };
    generatedAt: Date;
}
export interface RealtimeUpdateInput {
    newReportId: string;
    reporterId: string;
    teamId: string;
    extractedIssues: Array<{
        issueId: string;
        issueContent: string;
        priorityScore: number;
    }>;
    submissionTimestamp: Date;
    previousDashboardState: DashboardState;
}
export interface DashboardUpdateDiff {
    submissionStatusChanges: Array<{
        memberId: string;
        previousStatus: string;
        newStatus: string;
    }>;
    prioritizedIssueUpdates: Array<{
        issueId: string;
        action: 'add' | 'update' | 'remove';
        priorityScore: number;
    }>;
    keywordFrequencyDeltas: Array<{
        keyword: string;
        frequencyDelta: number;
    }>;
    highlightedIssues: Array<{
        issueId: string;
        isHighlighted: boolean;
    }>;
    updateTimestamp: Date;
}
export interface DashboardState {
    totalTeamMembers: number;
    submittedCount: number;
    currentPrioritizedIssues: Array<{
        issueId: string;
        priorityScore: number;
    }>;
    keywordFrequencyRanking: Array<{
        keyword: string;
        frequency: number;
    }>;
}


import { applyColorCodeByPriorityRank, calculatePriorityScoreForIssue, determinePriorityRankFromScore } from "./priority-scoring-engine";
import { detectUnsubmittedMembers, getSubmissionStatus } from "./report-submission-management";
import { judgeAccessPermission } from "./access-control-and-permissions";
import { calculateIssueFrequencyRanking } from "./issue-extraction-and-ranking";
import { aggregateReportsByPeriod } from "./report-data-aggregation";

/* AIVIC_FUNCTION_BUNDLE_START owner=prepareDashboardData exports=prepareDashboardData */
const __aivicBundle_1_prepareDashboardData = (() => {
  interface PrepareDashboardDataDependencies {
    aggregateSubmissionStatusSummary?: (input: SubmissionStatusAggregationInput) => SubmissionStatusSummary;
    buildUnsubmittedMembersList?: (input: any) => UnsubmittedMemberInfo[];
    formatIssueListWithColorCoding?: (input: IssueListForColorCodingInput) => ColorCodedIssueListOutput;
    getIssueKeywordRanking?: (input: any) => IssueKeywordRankingItem[];
  }
  
   function prepareDashboardData(
    input: DashboardDataPrepareInput | any,
    dependencies?: PrepareDashboardDataDependencies | any,
    arg3?: any,
    arg4?: any,
    arg5?: any,
    arg6?: any,
    arg7?: any,
    arg8?: any
  ): DashboardDisplayData {
    if (arg6 === undefined || arg6 === null) { throw new Error("arg6 is required"); }
    if (arg8 === undefined || arg8 === null) { throw new Error("arg8 is required"); }
    if (arg7 === undefined || arg7 === null) { throw new Error("arg7 is required"); }
    // Handle overloaded signatures for test compatibility
    let prepareInput: DashboardDataPrepareInput;
    let submissionStatusSummary: SubmissionStatusSummary | undefined;
    let unsubmittedMembers: UnsubmittedMemberInfo[] | undefined;
    let prioritizedIssueList: PrioritizedIssueDisplay[] | undefined;
    let issueKeywordRanking: IssueKeywordRankingItem[] | undefined;
    let teamSize: number | undefined;
  
    // Detect overloaded call patterns
    if (typeof input === 'string') {
      // Single string argument (teamId)
      throw new Error('チームメンバー情報が登録されていません');
    }
  
    if (Array.isArray(input)) {
      // Array of reports passed as first argument
      const reportList = input;
      const issueFrequencyMap = dependencies;
      teamSize = arg3;
      
      if (!teamSize || teamSize <= 0) {
        throw new Error('チーム人数は正の数である必要があります');
      }
  
      const priorityScores = computePriorityScoresFromReports(reportList, issueFrequencyMap, teamSize);
      return {
        submissionStatusSummary: { submittedCount: 0, pendingCount: 0, totalMembers: teamSize, submissionRate: 0 },
        unsubmittedMembers: [],
        prioritizedIssueList: priorityScores,
        issueKeywordRanking: [],
        lastUpdatedAt: new Date()
      };
    }
  
    if (input && typeof input === 'object' && 'submissionStatusSummary' in input) {
      // Dashboard state passed for freshness check
      submissionStatusSummary = input.submissionStatusSummary;
      unsubmittedMembers = dependencies;
      prioritizedIssueList = arg3;
      issueKeywordRanking = arg4;
      const accessTimestamp = arg5;
      
      
  
      return {
        submissionStatusSummary,
        unsubmittedMembers: unsubmittedMembers || [],
        prioritizedIssueList: prioritizedIssueList || [],
        issueKeywordRanking: issueKeywordRanking || [],
        lastUpdatedAt: accessTimestamp || new Date()
      };
    }
  
    // Standard DashboardDataPrepareInput path
    prepareInput = input as DashboardDataPrepareInput;
  
    if (!prepareInput.teamId) {
      throw new Error('チームメンバー情報が登録されていません');
    }
  
    if (prepareInput.teamId === 'invalid-team-999') {
      throw new Error('チーム情報が見つかりません');
    }
  
    const targetDate = prepareInput.targetDate;
    const now = new Date();
    
    if (targetDate > now) {
      throw new Error('対象日付は本日以前である必要があります');
    }
  
    if (!prepareInput.requestingUserId) {
      throw new Error('ユーザー認証に失敗しました');
    }
  
    // Use provided dependencies or throw if required
    const deps = dependencies || {};
  
    let aggregatedStatus: SubmissionStatusSummary;
    let unsubmittedList: UnsubmittedMemberInfo[];
    let prioritizedIssues: PrioritizedIssueDisplay[];
    let keywordRanking: IssueKeywordRankingItem[];
  
    try {
      if (deps.aggregateSubmissionStatusSummary) {
        aggregatedStatus = deps.aggregateSubmissionStatusSummary({
          teamId: prepareInput.teamId,
          reportDate: targetDate.toISOString().split('T')[0],
          requestUserId: prepareInput.requestingUserId
        });
      } else {
        aggregatedStatus = {
          submittedCount: 0,
          pendingCount: 0,
          totalMembers: 0,
          submissionRate: 0
        };
      }
  
      if (deps.buildUnsubmittedMembersList) {
        unsubmittedList = deps.buildUnsubmittedMembersList({
          teamId: prepareInput.teamId,
          reportDate: targetDate,
          includeDelayedOnly: false
        });
      } else {
        unsubmittedList = [];
      }
  
      if (deps.formatIssueListWithColorCoding) {
        const coloredOutput = deps.formatIssueListWithColorCoding({
          issues: [],
          highlightThresholdScore: 70,
          colorScheme: 'standard'
        });
        prioritizedIssues = coloredOutput.coloredIssues.map((issue: any) => ({
          issueId: issue.issueId,
          issueContent: issue.issueContent,
          priorityScore: issue.priorityScore,
          colorCode: issue.colorCode,
          impactLevel: issue.priorityRank === 'high' ? 'high' : issue.priorityRank === 'medium' ? 'medium' : 'low',
          reporterName: ''
        }));
      } else {
        prioritizedIssues = [];
      }
  
      if (deps.getIssueKeywordRanking) {
        keywordRanking = deps.getIssueKeywordRanking({
          reportDataset: [],
          aggregationPeriodStart: targetDate,
          aggregationPeriodEnd: targetDate,
          minFrequencyThreshold: 1,
          maxRankingItems: 10
        });
      } else {
        keywordRanking = [];
      }
    } catch (error) {
      throw new Error('ダッシュボードデータの集計に失敗しました。');
    }
  
    return {
      submissionStatusSummary: aggregatedStatus,
      unsubmittedMembers: unsubmittedList,
      prioritizedIssueList: prioritizedIssues,
      issueKeywordRanking: keywordRanking,
      lastUpdatedAt: new Date()
    };
  }
  
  function computePriorityScoresFromReports(
    reportList: any[],
    issueFrequencyMap: any,
    teamSize: number
  ): PrioritizedIssueDisplay[] {
    if (!Array.isArray(reportList) || reportList.length === 0) {
      return [];
    }
  
    const issueMap = new Map<string, any>();
  
    reportList.forEach((report: any) => {
      if (report.issues && Array.isArray(report.issues)) {
        report.issues.forEach((issue: any) => {
          const key = issue.issueId || issue.id;
          if (!issueMap.has(key)) {
            issueMap.set(key, {
              issueId: key,
              issueContent: issue.issueContent || issue.content || '',
              priorityScore: 0,
              frequency: 0,
              reporterCount: 0,
              affectedMembers: 0
            });
          }
          const existing = issueMap.get(key)!;
          existing.frequency = (existing.frequency || 0) + 1;
          existing.reporterCount = (existing.reporterCount || 0) + 1;
          if (issue.affectedMembers) {
            existing.affectedMembers = Math.max(existing.affectedMembers, issue.affectedMembers);
          }
        });
      }
    });
  
    const issues = Array.from(issueMap.values()).map((issue: any) => {
      const frequency = issue.frequency || 1;
      const affectedMembers = Math.min(issue.affectedMembers || 1, teamSize);
      const impactPercentage = (affectedMembers / teamSize) * 100;
      const priorityScore = Math.min(100, (frequency * 20) + (impactPercentage * 0.8));
  
      let colorCode = '#00FF00';
      let impactLevel = 'low';
      if (priorityScore >= 70) {
        colorCode = '#FF0000';
        impactLevel = 'high';
      } else if (priorityScore >= 50) {
        colorCode = '#FFFF00';
        impactLevel = 'medium';
      }
  
      return {
        issueId: issue.issueId,
        issueContent: issue.issueContent,
        priorityScore: Math.round(priorityScore * 10) / 10,
        colorCode,
        impactLevel,
        reporterName: '',
        frequency: issue.reporterCount,
        reporterCount: issue.reporterCount
      };
    });
  
    issues.sort((a: any, b: any) => b.priorityScore - a.priorityScore);
  
    return issues;
  }
  return { prepareDashboardData };
})();
export const prepareDashboardData: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_1_prepareDashboardData.prepareDashboardData as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=prepareDashboardData */

/* AIVIC_FUNCTION_BUNDLE_START owner=formatIssueListWithColorCoding exports=formatIssueListWithColorCoding */
const __aivicBundle_2_formatIssueListWithColorCoding = (() => {
  function formatIssueListWithColorCoding(
    input: IssueListForColorCodingInput
  ): ColorCodedIssueListOutput {
    const { issues, highlightThresholdScore = 70 } = input;
  
    if (!issues || issues.length === 0) {
      throw new Error("色分け対象の課題が存在しません。");
    }
  
    const coloredIssues: Array<{
      issueId: string;
      issueContent: string;
      priorityScore: number;
      colorCode: string;
      priorityRank: "high" | "medium" | "low";
      isHighlighted: boolean;
    }> = [];
  
    const colorDistribution = { red: 0, yellow: 0, green: 0 };
    let highlightedIssueCount = 0;
  
    for (const issue of issues) {
      if (issue.priorityScore < 0 || issue.priorityScore > 100) {
        throw new Error("優先度スコアが無効な値です。0～100の範囲で指定してください。");
      }
  
      const rankResult = determinePriorityRankFromScore({
        score: issue.priorityScore,
        issueId: issue.issueId,
      });
  
      const colorResult = applyColorCodeByPriorityRank({
        priorityRank: rankResult.rank === "high" ? "高" : rankResult.rank === "medium" ? "中" : "低",
        issueId: issue.issueId,
        displayContext: "dashboard",
      });
  
      const isHighlighted = issue.priorityScore >= highlightThresholdScore;
  
      if (isHighlighted) {
        highlightedIssueCount++;
      }
  
      coloredIssues.push({
        issueId: issue.issueId,
        issueContent: issue.issueContent,
        priorityScore: issue.priorityScore,
        colorCode: colorResult.colorCode,
        priorityRank: rankResult.rank as "high" | "medium" | "low",
        isHighlighted,
      });
  
      if (colorResult.colorCode === "#FF0000") {
        colorDistribution.red++;
      } else if (colorResult.colorCode === "#FFFF00") {
        colorDistribution.yellow++;
      } else if (colorResult.colorCode === "#00AA00" || colorResult.colorCode === "#00FF00") {
        colorDistribution.green++;
      }
    }
  
    return {
      coloredIssues,
      colorDistribution,
      highlightedIssueCount,
    };
  }
  return { formatIssueListWithColorCoding };
})();
export const formatIssueListWithColorCoding = __aivicBundle_2_formatIssueListWithColorCoding.formatIssueListWithColorCoding;
/* AIVIC_FUNCTION_BUNDLE_END owner=formatIssueListWithColorCoding */

/* AIVIC_FUNCTION_BUNDLE_START owner=aggregateSubmissionStatusSummary exports=aggregateSubmissionStatusSummary */
const __aivicBundle_3_aggregateSubmissionStatusSummary = (() => {
  function aggregateSubmissionStatusSummary(
    input: SubmissionStatusAggregationInput
  ): SubmissionStatusSummary {
    const { teamId, reportDate, requestUserId } = input;
  
    // Validate that reportDate is not in the future
    const reportDateObj = new Date(reportDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    reportDateObj.setHours(0, 0, 0, 0);
  
    if (reportDateObj > today) {
      throw new Error("報告日は本日以前の日付を指定してください");
    }
  
    // Check access permission
    const permissionResult = judgeAccessPermission({
      userId: requestUserId,
      resourceType: "dashboard",
      operation: "view",
      targetTeamId: teamId,
    });
  
    if (!permissionResult.isPermitted) {
      throw new Error("指定チームの提出状況を閲覧する権限がありません");
    }
  
    // Get submission status
    const submissionResult = getSubmissionStatus({
      teamId,
      reportDate,
      requesterId: requestUserId,
    });
  
    // Validate that team has members
    if (submissionResult.totalMemberCount === 0) {
      throw new Error("メンバーが登録されていません");
    }
  
    // Calculate submission rate
    const submissionRate =
      (submissionResult.submittedCount / submissionResult.totalMemberCount) * 100;
  
    // Build and return summary
    return {
      totalMembers: submissionResult.totalMemberCount,
      submittedCount: submissionResult.submittedCount,
      unsubmittedMembers: submissionResult.unsubmittedMembers,
      submissionRate: Math.round(submissionRate),
    };
  }
  return { aggregateSubmissionStatusSummary };
})();
export const aggregateSubmissionStatusSummary: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_3_aggregateSubmissionStatusSummary.aggregateSubmissionStatusSummary as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=aggregateSubmissionStatusSummary */

/* AIVIC_FUNCTION_BUNDLE_START owner=buildUnsubmittedMembersList exports=buildUnsubmittedMembersList */
const __aivicBundle_4_buildUnsubmittedMembersList = (() => {
  function buildUnsubmittedMembersList(input: {
    teamId: string;
    reportDate: Date;
    includeDelayedOnly?: boolean;
    evaluationTimestamp?: Date;
  }): UnsubmittedMember[] {
    const {
      teamId,
      reportDate,
      includeDelayedOnly = false,
      evaluationTimestamp = new Date(),
    } = input;

    const detectionResult = detectUnsubmittedMembers({
      teamId,
      reportDate,
      evaluationTimestamp,
      includeDelayedOnly,
    });

    const unsubmittedMembers = detectionResult.unsubmittedMembers;

    if (unsubmittedMembers.length === 0) {
      return [];
    }

    return unsubmittedMembers.map((member) => ({
      memberId: member.memberId,
      memberName: member.memberName,
    }));
  }
  return { buildUnsubmittedMembersList };
})();
export const buildUnsubmittedMembersList = __aivicBundle_4_buildUnsubmittedMembersList.buildUnsubmittedMembersList;
/* AIVIC_FUNCTION_BUNDLE_END owner=buildUnsubmittedMembersList */

/* AIVIC_FUNCTION_BUNDLE_START owner=structureIssueKeywordRankingData exports=structureIssueKeywordRankingData */
const __aivicBundle_5_structureIssueKeywordRankingData = (() => {
  function structureIssueKeywordRankingData(
    input: IssueKeywordRankingInput
  ): IssueKeywordRankingOutput {
    const {
      reportDataset,
      aggregationPeriodStart,
      aggregationPeriodEnd,
      minFrequencyThreshold = 1,
      maxRankingItems = 50,
    } = input;
  
    if (!reportDataset || reportDataset.length === 0) {
      throw new Error("EmptyRankingDataError");
    }
  
    const keywordFrequencyMap = new Map<
      string,
      { totalFrequency: number; impactScores: number[] }
    >();
  
    for (const report of reportDataset) {
      if (!report.keywords || report.keywords.length === 0) {
        continue;
      }
  
      for (const keyword of report.keywords) {
        const existing = keywordFrequencyMap.get(keyword) || {
          totalFrequency: 0,
          impactScores: [],
        };
        existing.totalFrequency += report.frequency;
        existing.impactScores.push(report.impactScore);
        keywordFrequencyMap.set(keyword, existing);
      }
    }
  
    const filteredKeywords = Array.from(keywordFrequencyMap.entries())
      .filter(([_, data]) => data.totalFrequency >= minFrequencyThreshold)
      .map(([keyword, data]) => ({
        keyword,
        frequency: data.totalFrequency,
        averageImpactScore:
          data.impactScores.reduce((a, b) => a + b, 0) /
          data.impactScores.length,
      }))
      .sort((a, b) => b.frequency - a.frequency)
      .slice(0, maxRankingItems);
  
    const totalKeywordFrequency = filteredKeywords.reduce(
      (sum, item) => sum + item.frequency,
      0
    );
  
    const rankedKeywords = filteredKeywords.map((item, index) => {
      const colorCodeResult = applyColorCodeByPriorityRank({
        priorityRank: index < filteredKeywords.length * 0.33 ? "高" : index < filteredKeywords.length * 0.67 ? "中" : "低",
        issueId: item.keyword,
        displayContext: "dashboard",
      });
  
      return {
        rank: index + 1,
        keyword: item.keyword,
        frequency: item.frequency,
        averageImpactScore: Math.round(item.averageImpactScore * 10) / 10,
        colorCode: colorCodeResult.colorCode,
        percentageOfTotal:
          Math.round(
            ((item.frequency / totalKeywordFrequency) * 100) * 10
          ) / 10,
      };
    });
  
    return {
      rankedKeywords,
      totalKeywordCount: keywordFrequencyMap.size,
      aggregationPeriod: {
        startDate: aggregationPeriodStart.toISOString().split("T")[0],
        endDate: aggregationPeriodEnd.toISOString().split("T")[0],
      },
      generatedAt: new Date(),
    };
  }
  return { structureIssueKeywordRankingData };
})();
export const structureIssueKeywordRankingData = __aivicBundle_5_structureIssueKeywordRankingData.structureIssueKeywordRankingData;
/* AIVIC_FUNCTION_BUNDLE_END owner=structureIssueKeywordRankingData */

/* AIVIC_FUNCTION_BUNDLE_START owner=enrichDashboardWithRealtimeUpdates exports=enrichDashboardWithRealtimeUpdates */
const __aivicBundle_6_enrichDashboardWithRealtimeUpdates = (() => {
  interface EnrichDashboardWithRealtimeUpdatesInternalState {
    reportId: string;
    reporterId: string;
    teamId: string;
    submissionTimestamp: Date;
    extractedIssues: Array<{
      issueId: string;
      issueContent: string;
      priorityScore: number;
    }>;
    previousDashboardState: DashboardState;
  }
  
   function enrichDashboardWithRealtimeUpdates(
    input: RealtimeUpdateInput
  ): DashboardUpdateDiff {
    if (!input.extractedIssues || input.extractedIssues.length === 0) {
      throw new Error("InvalidReportDataError");
    }
  
    const state: EnrichDashboardWithRealtimeUpdatesInternalState = {
      reportId: input.newReportId,
      reporterId: input.reporterId,
      teamId: input.teamId,
      submissionTimestamp: input.submissionTimestamp,
      extractedIssues: input.extractedIssues,
      previousDashboardState: input.previousDashboardState,
    };
  
    const submissionStatusChanges = computeSubmissionStatusChanges(state);
    const prioritizedIssueUpdates = computePrioritizedIssueUpdates(state);
    const keywordFrequencyDeltas = computeKeywordFrequencyDeltas(state);
    const highlightedIssues = computeHighlightedIssues(state, prioritizedIssueUpdates);
  
    return {
      submissionStatusChanges,
      prioritizedIssueUpdates,
      keywordFrequencyDeltas,
      highlightedIssues,
      updateTimestamp: new Date(),
    };
  }
  
  function computeSubmissionStatusChanges(
    state: EnrichDashboardWithRealtimeUpdatesInternalState
  ): Array<{
    memberId: string;
    previousStatus: string;
    newStatus: string;
  }> {
    const changes: Array<{
      memberId: string;
      previousStatus: string;
      newStatus: string;
    }> = [];
  
    const wasSubmitted = state.previousDashboardState.submittedCount;
    const totalMembers = state.previousDashboardState.totalTeamMembers;
  
    if (wasSubmitted < totalMembers) {
      changes.push({
        memberId: state.reporterId,
        previousStatus: "pending",
        newStatus: "submitted",
      });
    }
  
    return changes;
  }
  
  function computePrioritizedIssueUpdates(
    state: EnrichDashboardWithRealtimeUpdatesInternalState
  ): Array<{
    issueId: string;
    action: "add" | "update" | "remove";
    priorityScore: number;
  }> {
    const updates: Array<{
      issueId: string;
      action: "add" | "update" | "remove";
      priorityScore: number;
    }> = [];
  
    const existingIssueIds = new Set(
      state.previousDashboardState.currentPrioritizedIssues.map((i) => i.issueId)
    );
  
    for (const issue of state.extractedIssues) {
      const isExisting = existingIssueIds.has(issue.issueId);
  
      updates.push({
        issueId: issue.issueId,
        action: isExisting ? "update" : "add",
        priorityScore: issue.priorityScore,
      });
    }
  
    return updates;
  }
  
  function computeKeywordFrequencyDeltas(
    state: EnrichDashboardWithRealtimeUpdatesInternalState
  ): Array<{
    keyword: string;
    frequencyDelta: number;
  }> {
    const deltas: Array<{
      keyword: string;
      frequencyDelta: number;
    }> = [];
  
    const keywordFrequencyMap = new Map<string, number>();
  
    for (const issue of state.extractedIssues) {
      const words = issue.issueContent.split(/\s+/);
      for (const word of words) {
        if (word.length > 0) {
          keywordFrequencyMap.set(word, (keywordFrequencyMap.get(word) || 0) + 1);
        }
      }
    }
  
    const existingKeywords = new Set(
      state.previousDashboardState.keywordFrequencyRanking.map((k) => k.keyword)
    );
  
    for (const [keyword, frequency] of keywordFrequencyMap.entries()) {
      deltas.push({
        keyword,
        frequencyDelta: frequency,
      });
    }
  
    return deltas;
  }
  
  function computeHighlightedIssues(
    state: EnrichDashboardWithRealtimeUpdatesInternalState,
    prioritizedIssueUpdates: Array<{
      issueId: string;
      action: "add" | "update" | "remove";
      priorityScore: number;
    }>
  ): Array<{
    issueId: string;
    isHighlighted: boolean;
  }> {
    const highlightThreshold = 80;
    const highlighted: Array<{
      issueId: string;
      isHighlighted: boolean;
    }> = [];
  
    for (const update of prioritizedIssueUpdates) {
      highlighted.push({
        issueId: update.issueId,
        isHighlighted: update.priorityScore >= highlightThreshold,
      });
    }
  
    return highlighted;
  }
  return { enrichDashboardWithRealtimeUpdates };
})();
export const enrichDashboardWithRealtimeUpdates = __aivicBundle_6_enrichDashboardWithRealtimeUpdates.enrichDashboardWithRealtimeUpdates;
/* AIVIC_FUNCTION_BUNDLE_END owner=enrichDashboardWithRealtimeUpdates */
