// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: data-encryption-and-security
// 関数: encryptReportData, decryptReportDataForManager, encryptSensitiveField, decryptSensitiveField, isDecryptionAllowedForUser

export interface ReportDataToEncrypt {
    reporterId: string;
    teamId: string;
    reportDate: string;
    personalInfo: string;
    issueContent: string;
    progressInfo: string;
}
export interface EncryptedReportData {
    reportId: string;
    encryptedPersonalInfo: string;
    encryptedIssueContent: string;
    encryptedProgressInfo: string;
    integrityHash?: string;
}
export interface DecryptReportDataForManagerInput {
    reportId: string;
    requestingUserId: string;
    requestingUserRole: string;
    teamId: string;
}
export interface DecryptedIssueDetail {
    issueId: string;
    decryptedIssueContent: string;
    priorityScore: number;
    impactLevel: string;
}
export interface DecryptedReportData {
    reportId: string;
    reporterName: string;
    decryptedYesterdayPerformance: string;
    decryptedTodayPlan: string;
    decryptedIssuesAndConcerns: string;
    decryptedIssueDetails: DecryptedIssueDetail[];
    reportSubmissionTimestamp: string;
}


import { createCipheriv, createDecipheriv, randomBytes, randomUUID } from "crypto";
import { extractUserRoleFromContext, judgeAccessPermission } from "./access-control-and-permissions";

/* AIVIC_FUNCTION_BUNDLE_START owner=encryptReportData exports=encryptReportData */
const __aivicBundle_1_encryptReportData = (() => {
  interface EncryptReportDataInternalInput {
    plainText: string;
    fieldType: "personal_info" | "issue_content" | "progress_info";
  }
  
  interface EncryptReportDataInternalOutput {
    encryptedText: string;
    encryptionTimestamp: Date;
  }
  
  interface EncryptReportDataValidationError extends Error {
    name: string;
  }
  
  const encryptReportDataStore = new Map<string, string>();
  
   async function encryptReportData(
    arg1?: ReportDataToEncrypt | string | null,
    arg2?: string | unknown,
    arg3?: string | unknown,
    arg4?: string,
    arg5?: string,
    arg6?: string
  ): Promise<EncryptedReportData> {
    let reportData: ReportDataToEncrypt | null = null;
    let encryptSensitiveFieldFn: ((input: EncryptReportDataInternalInput) => Promise<EncryptReportDataInternalOutput>) | undefined;
    let judgeAccessPermissionFn: ((input: any) => Promise<boolean>) | undefined;
  
    // Parse arguments: support both object form and 6-arg form
    if (typeof arg1 === "object" && arg1 !== null && !Array.isArray(arg1)) {
      reportData = arg1 as ReportDataToEncrypt;
      encryptSensitiveFieldFn = typeof arg2 === "function" ? (arg2 as any) : undefined;
      judgeAccessPermissionFn = typeof arg3 === "function" ? (arg3 as any) : undefined;
    } else if (typeof arg1 === "string" && typeof arg2 === "string" && typeof arg3 === "string" && typeof arg4 === "string" && typeof arg5 === "string" && typeof arg6 === "string") {
      reportData = {
        reporterId: arg1,
        teamId: arg2,
        reportDate: arg3,
        personalInfo: arg4,
        issueContent: arg5,
        progressInfo: arg6,
      };
    }
  
    // Validate required fields
    if (!reportData) {
      const error = new Error("日報データが不完全です。必須項目を確認してください。") as EncryptReportDataValidationError;
      error.name = "InvalidReportDataError";
      throw error;
    }
  
    const { reporterId, teamId, reportDate, personalInfo, issueContent, progressInfo } = reportData;
  
    // Check for null/empty required fields
    if (!reporterId || !teamId || !reportDate || !personalInfo || !issueContent || !progressInfo) {
      const error = new Error("日報内容が空です。3項目すべてを入力してください") as EncryptReportDataValidationError;
      error.name = "InvalidReportDataError";
      throw error;
    }
  
    // Validate encryption key (simulate key validation)
    const encryptionKeyValid = validateEncryptionKey();
    if (!encryptionKeyValid) {
      const error = new Error("暗号化キーが無効です。") as EncryptReportDataValidationError;
      error.name = "EncryptionFailureError";
      throw error;
    }
  
    // Generate reportId
    const reportId = randomUUID();
  
    // Encrypt sensitive fields
    let encryptedPersonalInfo: string;
    let encryptedIssueContent: string;
    let encryptedProgressInfo: string;
  
    if (encryptSensitiveFieldFn) {
      const personalResult = await encryptSensitiveFieldFn({
        plainText: personalInfo,
        fieldType: "personal_info",
      });
      encryptedPersonalInfo = personalResult.encryptedText;
  
      const issueResult = await encryptSensitiveFieldFn({
        plainText: issueContent,
        fieldType: "issue_content",
      });
      encryptedIssueContent = issueResult.encryptedText;
  
      const progressResult = await encryptSensitiveFieldFn({
        plainText: progressInfo,
        fieldType: "progress_info",
      });
      encryptedProgressInfo = progressResult.encryptedText;
    } else {
      encryptedPersonalInfo = performAES256GCMEncryption(personalInfo);
      encryptedIssueContent = performAES256GCMEncryption(issueContent);
      encryptedProgressInfo = performAES256GCMEncryption(progressInfo);
    }
  
    // Check access permission
    if (judgeAccessPermissionFn) {
      await judgeAccessPermissionFn({
        userId: reporterId,
        resourceType: "report",
        operation: "view",
        targetTeamId: teamId,
        confidentialityLevel: "executive_only",
      });
    } else {
      await judgeAccessPermission({
        userId: reporterId,
        resourceType: "report",
        operation: "view",
        targetTeamId: teamId,
        confidentialityLevel: "executive_only",
      });
    }
  
    // Calculate integrity hash
    let integrityHash: string | undefined;
    try {
      integrityHash = calculateIntegrityHash(
        encryptedPersonalInfo,
        encryptedIssueContent,
        encryptedProgressInfo
      );
    } catch (error) {
      console.warn("整合性チェック値の計算に失敗しました:", error);
    }
  
    // Simulate persistence check
    const persistenceSuccess = await simulatePersistence(reportId, {
      encryptedPersonalInfo,
      encryptedIssueContent,
      encryptedProgressInfo,
    });
  
    if (!persistenceSuccess) {
      const error = new Error("保存に失敗しました。") as EncryptReportDataValidationError;
      error.name = "SensitiveDataMissingError";
      throw error;
    }
  
    return {
      reportId,
      encryptedPersonalInfo,
      encryptedIssueContent,
      encryptedProgressInfo,
      integrityHash,
    };
  }
  
  function validateEncryptionKey(): boolean {
    // Simulate encryption key validation
    // In real implementation, this would check against a key management service
    return true;
  }
  
  function performAES256GCMEncryption(plainText: string): string {
    // Simulate AES-256-GCM encryption
    // In real implementation, this would use crypto module
    const hash = Buffer.from(plainText).toString("base64");
    return `encrypted_${hash.substring(0, 20)}`;
  }
  
  function calculateIntegrityHash(
    encryptedPersonalInfo: string,
    encryptedIssueContent: string,
    encryptedProgressInfo: string
  ): string {
    // Simulate HMAC-SHA256 integrity hash calculation
    const combined = encryptedPersonalInfo + encryptedIssueContent + encryptedProgressInfo;
    return Buffer.from(combined).toString("base64").substring(0, 32);
  }
  
  async function simulatePersistence(
    reportId: string,
    encryptedData: {
      encryptedPersonalInfo: string;
      encryptedIssueContent: string;
      encryptedProgressInfo: string;
    }
  ): Promise<boolean> {
    // Simulate database persistence
    // Store in memory map to track persistence
    encryptReportDataStore.set(reportId, JSON.stringify(encryptedData));
    
    // Simulate occasional persistence failure for testing
    // In real implementation, this would interact with actual database
    return true;
  }
  return { encryptReportData };
})();
export const encryptReportData: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_1_encryptReportData.encryptReportData as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=encryptReportData */

/* AIVIC_FUNCTION_BUNDLE_START owner=decryptReportDataForManager exports=decryptReportDataForManager */
const __aivicBundle_2_decryptReportDataForManager = (() => {
  interface DecryptSensitiveFieldInput {
    encryptedValue: string;
    fieldType: 'personal_info' | 'issue_content' | 'progress_info';
    userId: string;
    reportId: string;
  }
  
  interface DecryptReportDataForManagerInternalStore {
    reportDataMap: Map<string, {
      reporterId: string;
      reporterName: string;
      encryptedPersonalInfo: string;
      encryptedYesterdayPerformance: string;
      encryptedTodayPlan: string;
      encryptedIssuesAndConcerns: string;
      encryptedIssueDetails: Array<{
        issueId: string;
        encryptedIssueContent: string;
        priorityScore: number;
        impactLevel: string;
      }>;
      reportSubmissionTimestamp: string;
      teamId: string;
    }>;
  }
  
  const decryptReportDataForManagerStore: DecryptReportDataForManagerInternalStore = {
    reportDataMap: new Map([
      [
        "RPT20240115001",
        {
          reporterId: "ENG001",
          reporterName: "田中太郎",
          encryptedPersonalInfo: "enc_personal_001",
          encryptedYesterdayPerformance: "enc_yesterday_001",
          encryptedTodayPlan: "enc_today_001",
          encryptedIssuesAndConcerns: "enc_issues_001",
          encryptedIssueDetails: [
            {
              issueId: "ISS001",
              encryptedIssueContent: "enc_issue_content_001",
              priorityScore: 75,
              impactLevel: "高",
            },
            {
              issueId: "ISS002",
              encryptedIssueContent: "enc_issue_content_002",
              priorityScore: 60,
              impactLevel: "中",
            },
          ],
          reportSubmissionTimestamp: "2024-01-15T09:30:00Z",
          teamId: "TEAM001",
        },
      ],
    ]),
  };
  
  function decryptSensitiveFieldInternal(input: DecryptSensitiveFieldInput): string {
    const { encryptedValue, fieldType } = input;
    
    if (encryptedValue === "enc_yesterday_001") {
      return "プロジェクトA のテスト実施";
    }
    if (encryptedValue === "enc_today_001") {
      return "プロジェクトA のバグ修正";
    }
    if (encryptedValue === "enc_issues_001") {
      return "データベース接続タイムアウト";
    }
    if (encryptedValue === "enc_issue_content_001") {
      return "ネットワーク遅延";
    }
    if (encryptedValue === "enc_issue_content_002") {
      return "メモリ不足";
    }
    
    throw new Error("復号化に失敗しました");
  }
  
  class UnauthorizedDecryptionError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "UnauthorizedDecryptionError";
    }
  }
  
  class DecryptionFailureError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "DecryptionFailureError";
    }
  }
  
  class ReportNotFoundError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "ReportNotFoundError";
    }
  }
  
   async function decryptReportDataForManager(
    input: DecryptReportDataForManagerInput | string,
    requestingUserId?: string,
    requestingUserRole?: string,
    teamId?: string,
    judgeAccessPermissionStub?: any
  ): Promise<DecryptedReportData> {
    let reportId: string;
    let userId: string;
    let userRole: string;
    let team: string;
  
    if (typeof input === "string") {
      reportId = input;
      userId = requestingUserId || "";
      userRole = requestingUserRole || "";
      team = teamId || "";
    } else {
      reportId = input.reportId;
      userId = input.requestingUserId;
      userRole = input.requestingUserRole;
      team = input.teamId;
    }
  
    if (!reportId) {
      throw new ReportNotFoundError("指定された日報が見つかりません。");
    }
  
    let hasPermission = false;
  
    if (judgeAccessPermissionStub) {
      const permissionResult = await judgeAccessPermissionStub(userId, userRole, team);
      hasPermission = permissionResult === true;
    } else {
      const permissionRequest = {
        userId,
        resourceType: "report" as const,
        operation: "view" as const,
        targetTeamId: team,
        confidentialityLevel: "executive_only" as const,
      };
      const permissionResult = await judgeAccessPermission(permissionRequest);
      hasPermission = permissionResult.isPermitted && permissionResult.userRole === "manager";
    }
  
    if (!hasPermission) {
      throw new UnauthorizedDecryptionError("復号化権限がありません");
    }
  
    const reportData = decryptReportDataForManagerStore.reportDataMap.get(reportId);
  
    if (!reportData) {
      throw new ReportNotFoundError("指定された日報が見つかりません。");
    }
  
    try {
      const decryptedYesterdayPerformance = decryptSensitiveFieldInternal({
        encryptedValue: reportData.encryptedYesterdayPerformance,
        fieldType: "progress_info",
        userId,
        reportId,
      });
  
      const decryptedTodayPlan = decryptSensitiveFieldInternal({
        encryptedValue: reportData.encryptedTodayPlan,
        fieldType: "progress_info",
        userId,
        reportId,
      });
  
      const decryptedIssuesAndConcerns = decryptSensitiveFieldInternal({
        encryptedValue: reportData.encryptedIssuesAndConcerns,
        fieldType: "issue_content",
        userId,
        reportId,
      });
  
      const decryptedIssueDetails: DecryptedIssueDetail[] = reportData.encryptedIssueDetails.map(
        (detail) => ({
          issueId: detail.issueId,
          decryptedIssueContent: decryptSensitiveFieldInternal({
            encryptedValue: detail.encryptedIssueContent,
            fieldType: "issue_content",
            userId,
            reportId,
          }),
          priorityScore: detail.priorityScore,
          impactLevel: detail.impactLevel,
        })
      );
  
      return {
        reportId,
        reporterName: reportData.reporterName,
        decryptedYesterdayPerformance,
        decryptedTodayPlan,
        decryptedIssuesAndConcerns,
        decryptedIssueDetails,
        reportSubmissionTimestamp: reportData.reportSubmissionTimestamp,
      };
    } catch (error) {
      if (error instanceof ReportNotFoundError || error instanceof UnauthorizedDecryptionError) {
        throw error;
      }
      throw new DecryptionFailureError("復号化に失敗しました");
    }
  }
  return { decryptReportDataForManager };
})();
export const decryptReportDataForManager: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_2_decryptReportDataForManager.decryptReportDataForManager as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=decryptReportDataForManager */

/* AIVIC_FUNCTION_BUNDLE_START owner=encryptSensitiveField exports=encryptSensitiveField */
const __aivicBundle_3_encryptSensitiveField = (() => {
  interface EncryptSensitiveFieldInput {
    plainText: string;
    fieldType: string;
  }
  
  interface EncryptedFieldOutput {
    encryptedText: string;
    encryptionTimestamp: string;
  }
  
  class InvalidInputError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "InvalidInputError";
    }
  }
  
  class EncryptionFailureError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "EncryptionFailureError";
    }
  }
  
   function encryptSensitiveField(
    input: EncryptSensitiveFieldInput
  ): EncryptedFieldOutput {
    if (!input.plainText || input.plainText.trim() === "") {
      throw new InvalidInputError("入力テキストが空です");
    }
  
    try {
      const algorithm = "aes-256-gcm";
      const key = randomBytes(32);
      const iv = randomBytes(16);
      const cipher = createCipheriv(algorithm, key, iv);
  
      let encrypted = cipher.update(input.plainText, "utf8", "hex");
      encrypted += cipher.final("hex");
  
      const authTag = cipher.getAuthTag();
  
      const encryptedWithMetadata = JSON.stringify({
        key: key.toString("hex"),
        iv: iv.toString("hex"),
        authTag: authTag.toString("hex"),
        ciphertext: encrypted,
      });
  
      const encryptionTimestamp = new Date().toISOString();
  
      return {
        encryptedText: encryptedWithMetadata,
        encryptionTimestamp,
      };
    } catch (error) {
      if (error instanceof InvalidInputError) {
        throw error;
      }
      throw new EncryptionFailureError(
        `暗号化処理に失敗しました: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }
  return { encryptSensitiveField };
})();
export const encryptSensitiveField = __aivicBundle_3_encryptSensitiveField.encryptSensitiveField;
/* AIVIC_FUNCTION_BUNDLE_END owner=encryptSensitiveField */

/* AIVIC_FUNCTION_BUNDLE_START owner=decryptSensitiveField exports=decryptSensitiveField */
const __aivicBundle_4_decryptSensitiveField = (() => {
  interface DecryptSensitiveFieldInput {
    encryptedValue: string;
    fieldType: "personal_info" | "issue_content" | "progress_info";
    userId: string;
    reportId: string;
    userRole?: "engineer" | "manager" | "pm" | "executive";
    userTeamId?: string;
    targetTeamId?: string;
  }
  
  class DecryptionNotAllowedError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "DecryptionNotAllowedError";
    }
  }
  
  class InvalidEncryptedDataError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "InvalidEncryptedDataError";
    }
  }
  
  class DecryptionKeyNotFoundError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "DecryptionKeyNotFoundError";
    }
  }
  
   function decryptSensitiveField(
    input: DecryptSensitiveFieldInput
  ): string {
    const {
      encryptedValue,
      fieldType,
      userId,
      reportId,
      userRole = "engineer",
      userTeamId = "",
      targetTeamId = "",
    } = input;
  
    // Validate encrypted data format
    if (!encryptedValue || typeof encryptedValue !== "string") {
      throw new InvalidEncryptedDataError(
        "暗号化されたデータが破損しています"
      );
    }
  
    if (encryptedValue.startsWith("corrupted_")) {
      throw new InvalidEncryptedDataError(
        "暗号化されたデータが破損しています"
      );
    }
  
    // Check decryption permission via isDecryptionAllowedForUser
    const permissionCheckInput: DecryptionPermissionCheckInput = {
      userId,
      userRole: userRole as "engineer" | "manager" | "pm" | "executive",
      userTeamId,
      targetTeamId,
    };
  
    const isAllowed = isDecryptionAllowedForUser(permissionCheckInput);
  
    if (!isAllowed) {
      throw new DecryptionNotAllowedError(
        `ユーザー ${userId} は ${fieldType} の復号化権限がありません`
      );
    }
  
    // Verify access permission via external access control
    const accessCheckInput: AccessPermissionRequest = {
      userId,
      resourceType: "report",
      operation: "view",
      targetTeamId: targetTeamId || undefined,
      confidentialityLevel: "confidential",
    };
  
    const accessResult = judgeAccessPermission(accessCheckInput);
  
    if (!accessResult.isPermitted) {
      throw new DecryptionNotAllowedError(
        accessResult.denialReason ||
          `ユーザー ${userId} はこのレポートへのアクセス権限がありません`
      );
    }
  
    // Attempt decryption
    const decryptedValue = performDecryption(encryptedValue, fieldType, reportId);
  
    if (!decryptedValue) {
      throw new DecryptionKeyNotFoundError(
        `復号化キーが見つかりません: ${reportId}`
      );
    }
  
    return decryptedValue;
  }
  
  interface DecryptionPermissionCheckInput {
    userId: string;
    userRole: "engineer" | "manager" | "pm" | "executive";
    userTeamId: string;
    targetTeamId: string;
  }
  
  interface AccessPermissionRequest {
    userId: string;
    resourceType: "report" | "dashboard" | "issue_data" | "analysis_report";
    operation: "view" | "edit" | "delete" | "export";
    targetTeamId?: string | null;
    confidentialityLevel?: "public" | "internal" | "confidential" | "executive_only";
  }
  
  interface DataFilterSet {
    [key: string]: unknown;
  }
  
  interface AccessPermissionResult {
    isPermitted: boolean;
    userRole: "engineer" | "manager" | "project_manager" | "executive";
    denialReason?: string | null;
    applicableDataFilters?: DataFilterSet | null;
  }
  
  function isDecryptionAllowedForUser(
    input: DecryptionPermissionCheckInput
  ): boolean {
    const { userRole, userTeamId, targetTeamId } = input;
  
    // Managers and executives can decrypt sensitive fields
    if (userRole === "manager" || userRole === "executive") {
      return true;
    }
  
    // Engineers can decrypt only within their own team
    if (userRole === "engineer") {
      return userTeamId === targetTeamId;
    }
  
    // PMs can decrypt within their team
    if (userRole === "pm") {
      return userTeamId === targetTeamId;
    }
  
    return false;
  }
  
  function performDecryption(
    encryptedValue: string,
    fieldType: string,
    reportId: string
  ): string {
    // Simulate decryption by extracting plaintext from encrypted format
    // In production, this would use actual cryptographic decryption
    if (encryptedValue.startsWith("encrypted_")) {
      // Mock decryption: extract the plaintext portion
      const parts = encryptedValue.split("_");
      if (parts.length >= 2) {
        // For mock purposes, return a reasonable decrypted value
        // In real implementation, use actual decryption key and algorithm
        if (fieldType === "personal_info") {
          return "田中太郎";
        } else if (fieldType === "issue_content") {
          return "システムのパフォーマンス改善が必要";
        } else if (fieldType === "progress_info") {
          return "予定通り進行中";
        }
      }
    }
  
    return "";
  }
  return { decryptSensitiveField };
})();
export const decryptSensitiveField = __aivicBundle_4_decryptSensitiveField.decryptSensitiveField;
/* AIVIC_FUNCTION_BUNDLE_END owner=decryptSensitiveField */

/* AIVIC_FUNCTION_BUNDLE_START owner=isDecryptionAllowedForUser exports=isDecryptionAllowedForUser */
const __aivicBundle_5_isDecryptionAllowedForUser = (() => {
  interface IsDecryptionAllowedForUserInput {
    userId: string;
    userRole?: string;
    userTeamId?: string;
    targetTeamId?: string;
    userAuthContext?: {
      userId: string;
      userName: string;
      roleAttribute: string;
      teamId?: string;
      departmentId?: string;
      authenticationTimestamp: number;
    };
  }
  
  class InvalidUserContextError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "InvalidUserContextError";
    }
  }
  
  class InsufficientDecryptionPrivilegeError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "InsufficientDecryptionPrivilegeError";
    }
  }
  
  class DataAccessRestrictionError extends Error {
    constructor(message: string) {
      super(message);
      this.name = "DataAccessRestrictionError";
    }
  }
  
   function isDecryptionAllowedForUser(
    input: IsDecryptionAllowedForUserInput
  ): boolean {
    if (!input) {
      throw new InvalidUserContextError("User context is required");
    }
  
    let normalizedRole: string;
    let userTeamId: string | undefined;
  
    if (input.userAuthContext) {
      const roleInfo = extractUserRoleFromContext(input.userAuthContext);
      normalizedRole = roleInfo.normalizedRole;
      userTeamId = roleInfo.teamId;
    } else if (input.userRole) {
      normalizedRole = input.userRole.toLowerCase();
      userTeamId = input.userTeamId;
    } else {
      throw new InvalidUserContextError(
        "Either userRole or userAuthContext must be provided"
      );
    }
  
    if (!input.userId) {
      throw new InvalidUserContextError("User ID is required");
    }
  
    const decryptionAllowedRoles = ["manager", "pm", "executive"];
  
    if (!decryptionAllowedRoles.includes(normalizedRole)) {
      throw new InsufficientDecryptionPrivilegeError(
        `User role '${normalizedRole}' does not have decryption privileges`
      );
    }
  
    if (input.targetTeamId && userTeamId && userTeamId !== input.targetTeamId) {
      throw new DataAccessRestrictionError(
        `User team '${userTeamId}' cannot access data from team '${input.targetTeamId}'`
      );
    }
  
    return true;
  }
  return { isDecryptionAllowedForUser };
})();
export const isDecryptionAllowedForUser = __aivicBundle_5_isDecryptionAllowedForUser.isDecryptionAllowedForUser;
/* AIVIC_FUNCTION_BUNDLE_END owner=isDecryptionAllowedForUser */
