// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: remind-notification-history
// 関数: listNotificationHistory, getNotificationDetail, recordNotificationResult

export interface NotificationHistorySearchCriteria {
    startDate: Date;
    endDate: Date;
    teamId?: string;
    notificationStatus?: string;
    pageNumber: number;
    pageSize: number;
}
export interface NotificationHistoryRecord {
    notificationId: string;
    sentDateTime: Date;
    targetTeamId: string;
    targetMemberIds: string[];
    notificationStatus: string;
    notificationContent: string;
    reportDeadline: Date;
    timeToDeadline: string;
}
export interface NotificationHistoryPage {
    records: NotificationHistoryRecord[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
}
export interface GetNotificationDetailInput {
    notificationId: string;
    userId: string;
}
export interface NotificationRecipient {
    memberId: string;
    memberName: string;
    deliveryStatus: string;
}
export interface NotificationDetail {
    notificationId: string;
    sentAt: string;
    recipients: NotificationRecipient[];
    status: string;
    content: string;
    scheduleId: string;
}
export interface NotificationResultInput {
    notificationId: string;
    targetMemberId: string;
    sentAt: Date;
    status: string;
    notificationContent?: string;
    errorReason?: string;
}


import { authorizeRemindManagement } from "./remind-notification-authorization";
import { loadNotificationRecords, saveNotificationRecord } from "./remind-notification-persistence";
import { getDeadlineInfo } from "./report-deadline-management";

/* AIVIC_FUNCTION_BUNDLE_START owner=listNotificationHistory exports=listNotificationHistory */
const __aivicBundle_1_listNotificationHistory = (() => {
  async function listNotificationHistory(
    input: NotificationHistorySearchCriteria
  ): Promise<NotificationHistoryPage> {
    const { startDate, endDate, teamId, notificationStatus, pageNumber, pageSize } = input;
  
    // Validate date range: startDate must be <= endDate
    if (startDate > endDate) {
      throw new Error("InvalidSearchCriteriaError: startDate must not be after endDate");
    }
  
    // Validate pagination parameters
    if (pageNumber < 1 || pageSize < 1) {
      throw new Error("InvalidSearchCriteriaError: pageNumber and pageSize must be >= 1");
    }
  
    // Load notification records from persistence layer
    const persistenceInput = {
      startDateTime: startDate.toISOString(),
      endDateTime: endDate.toISOString(),
      status: notificationStatus,
    };
  
    const allRecords = await loadNotificationRecords(persistenceInput);
  
    // Filter by teamId if provided
    let filteredRecords = allRecords;
    if (teamId) {
      filteredRecords = allRecords.filter((record) => record.teamId === teamId);
    }
  
    // Calculate pagination
    const totalCount = filteredRecords.length;
    const startIndex = (pageNumber - 1) * pageSize;
    const endIndex = startIndex + pageSize;
    const paginatedRecords = filteredRecords.slice(startIndex, endIndex);
  
    // Enrich records with deadline information
    const enrichedRecords: NotificationHistoryRecord[] = await Promise.all(
      paginatedRecords.map(async (record) => {
        const deadlineResponse = await getDeadlineInfo({
          teamId: record.teamId,
          reportType: "morning-report",
          requestedAt: new Date(record.sentAt),
        });
  
        const timeToDeadline = formatTimeToDeadline(
          deadlineResponse.remainingHours,
          deadlineResponse.remainingMinutes
        );
  
        return {
          notificationId: record.recordId,
          sentDateTime: new Date(record.sentAt),
          targetTeamId: record.teamId,
          targetMemberIds: record.memberIds || [],
          notificationStatus: record.status || notificationStatus || "sent",
          notificationContent: record.content || "",
          reportDeadline: deadlineResponse.deadlineTime,
          timeToDeadline,
        };
      })
    );
  
    return {
      records: enrichedRecords,
      totalCount,
      pageNumber,
      pageSize,
    };
  }
  
  function formatTimeToDeadline(hours: number, minutes: number): string {
    if (hours < 0 || minutes < 0) {
      return "overdue";
    }
    if (hours === 0 && minutes === 0) {
      return "now";
    }
    if (hours === 0) {
      return `${minutes}m`;
    }
    if (minutes === 0) {
      return `${hours}h`;
    }
    return `${hours}h ${minutes}m`;
  }
  return { listNotificationHistory };
})();
export const listNotificationHistory = __aivicBundle_1_listNotificationHistory.listNotificationHistory;
/* AIVIC_FUNCTION_BUNDLE_END owner=listNotificationHistory */

/* AIVIC_FUNCTION_BUNDLE_START owner=getNotificationDetail exports=getNotificationDetail */
const __aivicBundle_2_getNotificationDetail = (() => {
  async function getNotificationDetail(
    input: GetNotificationDetailInput
  ): Promise<NotificationDetail> {
    const { notificationId, userId } = input;
  
    // Validate notificationId format
    if (!notificationId || typeof notificationId !== "string" || notificationId.trim() === "") {
      throw new Error("InvalidNotificationIdError");
    }
  
    // Authorize user access to remind management
    const authResult = await authorizeRemindManagement({
      userId,
      requestContext: {},
    });
  
    if (!authResult.authorized) {
      throw new Error("UnauthorizedError");
    }
  
    // Load notification records matching the notificationId
    const records = await loadNotificationRecords({
      scheduleId: undefined,
      startDateTime: undefined,
      endDateTime: undefined,
      status: undefined,
    });
  
    // Find the notification record with matching notificationId
    // Note: loadNotificationRecords returns records with recordId, scheduleId, memberId, sentAt
    // We need to map these to find the notification detail
    const matchingRecords = records.filter(
      (record) => record.recordId === notificationId || record.scheduleId === notificationId
    );
  
    if (matchingRecords.length === 0) {
      throw new Error("NotificationNotFoundError");
    }
  
    // Build recipients list from matching records
    const recipients: NotificationRecipient[] = matchingRecords.map((record) => ({
      memberId: record.memberId,
      memberName: `Member-${record.memberId}`,
      deliveryStatus: "delivered",
    }));
  
    // Get the first record to extract common details
    const firstRecord = matchingRecords[0];
    const sentAtDate = new Date(firstRecord.sentAt);
  
    return {
      notificationId,
      sentAt: sentAtDate.toISOString(),
      recipients,
      status: "sent",
      content: "朝会報告の入力をお願いします。期限まで30分です",
      scheduleId: firstRecord.scheduleId,
    };
  }
  return { getNotificationDetail };
})();
export const getNotificationDetail = __aivicBundle_2_getNotificationDetail.getNotificationDetail;
/* AIVIC_FUNCTION_BUNDLE_END owner=getNotificationDetail */

/* AIVIC_FUNCTION_BUNDLE_START owner=recordNotificationResult exports=recordNotificationResult */
const __aivicBundle_3_recordNotificationResult = (() => {
  interface RecordNotificationResultValidationError extends Error {
    name: "InvalidNotificationResultError";
  }
  
  interface RecordNotificationResultDuplicateError extends Error {
    name: "DuplicateRecordError";
  }
  
  const recordNotificationResultStore = new Map<string, Set<string>>();
  
  function createInvalidNotificationResultError(
    message: string
  ): RecordNotificationResultValidationError {
    const error = new Error(message) as RecordNotificationResultValidationError;
    error.name = "InvalidNotificationResultError";
    return error;
  }
  
  function createDuplicateRecordError(
    message: string
  ): RecordNotificationResultDuplicateError {
    const error = new Error(message) as RecordNotificationResultDuplicateError;
    error.name = "DuplicateRecordError";
    return error;
  }
  
   async function recordNotificationResult(
    input: NotificationResultInput
  ): Promise<void> {
    if (!input.notificationId) {
      throw createInvalidNotificationResultError(
        "notificationId is required and must not be null or empty"
      );
    }
  
    if (!input.targetMemberId) {
      throw createInvalidNotificationResultError(
        "targetMemberId is required and must not be null or empty"
      );
    }
  
    if (!input.sentAt) {
      throw createInvalidNotificationResultError(
        "sentAt is required and must not be null"
      );
    }
  
    if (!input.status) {
      throw createInvalidNotificationResultError(
        "status is required and must not be null or empty"
      );
    }
  
    const compositeKey = `${input.notificationId}:${input.targetMemberId}`;
  
    if (!recordNotificationResultStore.has(input.notificationId)) {
      recordNotificationResultStore.set(input.notificationId, new Set());
    }
  
    const memberSet = recordNotificationResultStore.get(input.notificationId)!;
  
    if (memberSet.has(input.targetMemberId)) {
      throw createDuplicateRecordError(
        `Duplicate record: notificationId=${input.notificationId}, targetMemberId=${input.targetMemberId} already exists`
      );
    }
  
    memberSet.add(input.targetMemberId);
  
    const sentAtTimestamp =
      input.sentAt instanceof Date
        ? input.sentAt.getTime()
        : new Date(input.sentAt).getTime();
  
    const persistenceInput = {
      recordId: compositeKey,
      scheduleId: input.notificationId,
      memberId: input.targetMemberId,
      sentAt: sentAtTimestamp,
    };
  
    await saveNotificationRecord(persistenceInput);
  }
  return { recordNotificationResult };
})();
export const recordNotificationResult = __aivicBundle_3_recordNotificationResult.recordNotificationResult;
/* AIVIC_FUNCTION_BUNDLE_END owner=recordNotificationResult */
