// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: remind-notification-sender
// 関数: sendRemindNotifications, resolveNotificationTargets, buildNotificationMessage

export interface SendRemindNotificationsInput {
    scheduleId: string;
    userId: string;
    executionTimestamp: number;
}
export interface SendRemindNotificationsOutput {
    scheduleId: string;
    totalCount: number;
    successCount: number;
    failureCount: number;
}
export interface NotificationTarget {
    memberId: string;
    memberName: string;
    teamId: string;
    notificationChannel: string;
}
export interface NotificationMessageInput {
    teamName: string;
    memberName: string;
    reportDeadline: Date;
    scheduleId: string;
}
export interface NotificationMessage {
    subject: string;
    body: string;
    timeToDeadlineMinutes: number;
    recipientMemberId: string;
}
export interface ScheduleConfig {
    scheduleId: string;
    teamIds: string[];
    isEnabled: boolean;
}
export interface NotificationRecord {
    recordId: string;
    scheduleId: string;
    memberId: string;
    sentAt: number;
}


import { authorizeRemindManagement } from "./remind-notification-authorization";
import { listTeamMembers } from "./team-member-selection";
import { calculateTimeToDeadline, getDeadlineInfo } from "./report-deadline-management";
import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=sendRemindNotifications exports=sendRemindNotifications */
const __aivicBundle_1_sendRemindNotifications = (() => {
  async function sendRemindNotifications(
    input: SendRemindNotificationsInput
  ): Promise<SendRemindNotificationsOutput> {
    const { scheduleId, userId, executionTimestamp } = input;
  
    // Step 1: 権限検証
    const authResult = await authorizeRemindManagement({
      userId,
      requestContext: { scheduleId, executionTimestamp },
    });
  
    if (!authResult.authorized) {
      throw new Error(
        `UnauthorizedOperationError: User ${userId} is not authorized to send remind notifications`
      );
    }
  
    // Step 2: スケジュール設定を取得（実装では仮定）
    const scheduleConfig: ScheduleConfig = {
      scheduleId,
      teamIds: [],
      isEnabled: true,
    };
  
    // Step 3: 通知対象を解決
    const notificationTargets = resolveNotificationTargets(scheduleConfig);
  
    // Step 4: 各対象へ通知を送信
    let successCount = 0;
    let failureCount = 0;
  
    for (const target of notificationTargets) {
      try {
        // 報告期限情報を取得
        const deadlineInfo = await getDeadlineInfo({
          teamId: target.teamId,
          reportType: "morning-report",
          requestedAt: new Date(executionTimestamp * 1000),
        });
  
        // メッセージを構築
        const messageInput: NotificationMessageInput = {
          teamName: target.teamId,
          memberName: target.memberName,
          reportDeadline: deadlineInfo.deadlineTime,
          scheduleId,
        };
  
        buildNotificationMessage(messageInput);
  
        // 通知を送信（実装では Adapter を使用）
        const _recordId = randomUUID();
  
        successCount++;
      } catch (error) {
        failureCount++;
      }
    }
  
    // Step 5: 結果を返す
    return {
      scheduleId,
      totalCount: notificationTargets.length,
      successCount,
      failureCount,
    };
  }
  return { sendRemindNotifications };
})();
export const sendRemindNotifications = __aivicBundle_1_sendRemindNotifications.sendRemindNotifications;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendRemindNotifications */

/* AIVIC_FUNCTION_BUNDLE_START owner=resolveNotificationTargets exports=resolveNotificationTargets */
const __aivicBundle_2_resolveNotificationTargets = (() => {
  interface ResolveNotificationTargetsStore {
    seenMemberIds: Set<string>;
    targets: NotificationTarget[];
  }
  
   async function resolveNotificationTargets(
    input: ScheduleConfig
  ): Promise<NotificationTarget[]> {
    if (input["scheduleId"] === undefined || input["scheduleId"] === null) { throw new Error("scheduleId is required"); }
    if (!input.isEnabled) {
      throw new Error("Schedule is not enabled");
    }
  
    if (!input.teamIds || input.teamIds.length === 0) {
      throw new Error("NoValidTargetsError: No teams specified in schedule");
    }
  
    const store: ResolveNotificationTargetsStore = {
      seenMemberIds: new Set<string>(),
      targets: [],
    };
  
    for (const teamId of input.teamIds) {
      const teamMembersOutput = await listTeamMembers({
        teamId,
        includeInactive: false,
      });
  
      for (const member of teamMembersOutput.members) {
        if (!store.seenMemberIds.has(member.memberId)) {
          store.seenMemberIds.add(member.memberId);
          store.targets.push({
            memberId: member.memberId,
            memberName: member.memberName,
            teamId: teamId,
            notificationChannel: member.notificationChannel,
          });
        }
      }
    }
  
    if (store.targets.length === 0) {
      throw new Error("NoValidTargetsError: No valid notification targets found");
    }
  
    return store.targets;
  }
  return { resolveNotificationTargets };
})();
export const resolveNotificationTargets = __aivicBundle_2_resolveNotificationTargets.resolveNotificationTargets;
/* AIVIC_FUNCTION_BUNDLE_END owner=resolveNotificationTargets */

/* AIVIC_FUNCTION_BUNDLE_START owner=buildNotificationMessage exports=buildNotificationMessage */
const __aivicBundle_3_buildNotificationMessage = (() => {
  function buildNotificationMessage(
    input: NotificationMessageInput
  ): NotificationMessage {
    if (!input.teamName || input.teamName.trim() === "") {
      throw new Error("MissingTeamMemberInfoError");
    }
  
    if (!input.memberName || input.memberName.trim() === "") {
      throw new Error("MissingTeamMemberInfoError");
    }
  
    const deadlineInfo = calculateTimeToDeadline({
      deadlineDateTime: input.reportDeadline,
    });
  
    const subject = "朝会報告入力のお願い";
  
    const body = `${input.teamName}の${input.memberName}さんへ。朝会報告の入力をお願いします。期限まで${deadlineInfo.remainingMinutes}分です。`;
  
    return {
      subject,
      body,
      timeToDeadlineMinutes: deadlineInfo.remainingMinutes,
      recipientMemberId: input.scheduleId,
    };
  }
  return { buildNotificationMessage };
})();
export const buildNotificationMessage = __aivicBundle_3_buildNotificationMessage.buildNotificationMessage;
/* AIVIC_FUNCTION_BUNDLE_END owner=buildNotificationMessage */
