// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: remind-notification-scheduler
// 関数: initializeScheduler, triggerScheduledNotification

export interface SchedulerInitializationResult {
    success: boolean;
    registeredScheduleCount: number;
    failedScheduleIds: string[];
    nextExecutionTime?: string;
}
export interface ScheduledNotificationTriggerInput {
    scheduleId: string;
    executionTime: Date;
}
export interface ScheduledNotificationTriggerOutput {
    scheduleId: string;
    notificationsSent: number;
    executionStatus: string;
}
export interface RemindSchedule {
    scheduleId: string;
    scheduledTime: string;
    teamMemberIds: string[];
    reportDeadline: Date;
    isActive: boolean;
}
export interface NotificationSendResult {
    memberId: string;
    sent: boolean;
    errorMessage?: string;
}


import { listRemindSchedules, validateScheduleConfig } from "./remind-schedule-management";
import { loadSchedule } from "./remind-notification-persistence";
import { sendRemindNotifications } from "./remind-notification-sender";

/* AIVIC_FUNCTION_BUNDLE_START owner=initializeScheduler exports=initializeScheduler */
const __aivicBundle_1_initializeScheduler = (() => {
  function initializeScheduler(): SchedulerInitializationResult {
    const registeredSchedules: string[] = [];
    const failedScheduleIds: string[] = [];
    let nextExecutionTime: string | undefined;
  
    try {
      const listResult = listRemindSchedules({
        userId: "system",
        filterStatus: "enabled",
      });
  
      if (!listResult.schedules || listResult.schedules.length === 0) {
        return {
          success: false,
          registeredScheduleCount: 0,
          failedScheduleIds: [],
          nextExecutionTime: undefined,
        };
      }
  
      let earliestExecutionTime: Date | null = null;
  
      for (const scheduleItem of listResult.schedules) {
        try {
          const scheduleDetail = loadSchedule({
            scheduleId: scheduleItem.scheduleId,
          });
  
          const validationInput = {
            sendTime: scheduleDetail.sendTime,
            selectedTeamIds: scheduleDetail.targetTeamIds || [],
            selectedMemberIds: scheduleDetail.targetMemberIds || [],
            reportDeadlineTime: scheduleDetail.reportDeadlineTime || "",
          };
  
          const validationResult = validateScheduleConfig(validationInput);
  
          if (validationResult.isValid) {
            registeredSchedules.push(scheduleDetail.scheduleId);
  
            const sendTimeDate = new Date(scheduleDetail.sendTime);
            if (
              !isNaN(sendTimeDate.getTime()) &&
              (!earliestExecutionTime ||
                sendTimeDate < earliestExecutionTime)
            ) {
              earliestExecutionTime = sendTimeDate;
            }
          } else {
            failedScheduleIds.push(scheduleDetail.scheduleId);
          }
        } catch {
          failedScheduleIds.push(scheduleItem.scheduleId);
        }
      }
  
      if (earliestExecutionTime) {
        nextExecutionTime = earliestExecutionTime.toISOString();
      }
  
      const success =
        failedScheduleIds.length === 0 || registeredSchedules.length > 0;
  
      return {
        success,
        registeredScheduleCount: registeredSchedules.length,
        failedScheduleIds,
        nextExecutionTime,
      };
    } catch {
      return {
        success: false,
        registeredScheduleCount: 0,
        failedScheduleIds: [],
        nextExecutionTime: undefined,
      };
    }
  }
  return { initializeScheduler };
})();
export const initializeScheduler = __aivicBundle_1_initializeScheduler.initializeScheduler;
/* AIVIC_FUNCTION_BUNDLE_END owner=initializeScheduler */

/* AIVIC_FUNCTION_BUNDLE_START owner=triggerScheduledNotification exports=triggerScheduledNotification */
const __aivicBundle_2_triggerScheduledNotification = (() => {
  function triggerScheduledNotification(
    input: ScheduledNotificationTriggerInput
  ): ScheduledNotificationTriggerOutput {
    const { scheduleId, executionTime } = input;
  
    try {
      // スケジュール情報を取得（userId は空文字列で全スケジュール対象）
      const scheduleListResult = listRemindSchedules({
        userId: "",
        filterStatus: "active",
      });
  
      // 指定された scheduleId に該当するスケジュールを検索
      const targetSchedule = scheduleListResult.schedules.find(
        (schedule) => schedule.scheduleId === scheduleId
      );
  
      if (!targetSchedule) {
        // スケジュールが見つからない場合は failure
        return {
          scheduleId,
          notificationsSent: 0,
          executionStatus: "failure",
        };
      }
  
      // リマインド通知を送信
      const executionTimestamp = executionTime.getTime();
      const notificationResult = sendRemindNotifications({
        scheduleId,
        userId: "", // 複数ユーザーへの送信を示す
        executionTimestamp,
      });
  
      const successCount = notificationResult.successCount;
      const failureCount = notificationResult.failureCount;
  
      // 実行ステータスを判定
      let executionStatus: string;
      if (failureCount === 0 && successCount > 0) {
        executionStatus = "success";
      } else if (successCount > 0 && failureCount > 0) {
        executionStatus = "partial_failure";
      } else {
        executionStatus = "failure";
      }
  
      return {
        scheduleId,
        notificationsSent: successCount,
        executionStatus,
      };
    } catch (error) {
      // エラーが発生した場合は failure
      return {
        scheduleId,
        notificationsSent: 0,
        executionStatus: "failure",
      };
    }
  }
  return { triggerScheduledNotification };
})();
export const triggerScheduledNotification = __aivicBundle_2_triggerScheduledNotification.triggerScheduledNotification;
/* AIVIC_FUNCTION_BUNDLE_END owner=triggerScheduledNotification */
