// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: remind-schedule-management
// 関数: createRemindSchedule, updateRemindSchedule, toggleRemindScheduleStatus, listRemindSchedules, validateScheduleConfig

export interface RemindSchedule {
    scheduleId: string;
    scheduleName: string;
    sendTime: string;
    targetTeamIds: string[];
    targetMemberIds: string[];
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
}
export interface ValidationResult {
    isValid: boolean;
    errors?: Array<{
        field: string;
        message: string;
    }>;
}
export interface RemindScheduleItem {
    scheduleId: string;
    sendTime: string;
    targetTeams: string[];
    targetMembers: string[];
    isActive: boolean;
    timeToDeadline: number;
    createdAt: string;
    updatedAt: string;
}


import { randomUUID } from "crypto";
import { authorizeRemindManagement, authorizeScheduleOperation } from "./remind-notification-authorization";
import { loadSchedule, saveSchedule } from "./remind-notification-persistence";
import { getDeadlineInfo } from "./report-deadline-management";
import { listAvailableTeams, listTeamMembers } from "./team-member-selection";

/* AIVIC_FUNCTION_BUNDLE_START owner=createRemindSchedule exports=createRemindSchedule */
const __aivicBundle_1_createRemindSchedule = (() => {
  interface CreateRemindScheduleInput {
    scheduleName: string;
    sendTime: string;
    targetTeamIds: string[];
    targetMemberIds: string[];
    isEnabled: boolean;
    userId?: string;
    reportDeadlineTime?: string;
  }
  
   function createRemindSchedule(input: CreateRemindScheduleInput): RemindSchedule {
    const scheduleId = `sched_${randomUUID()}`;
    const now = new Date().toISOString();
  
    const validationInput = {
      sendTime: input.sendTime,
      selectedTeamIds: input.targetTeamIds,
      selectedMemberIds: input.targetMemberIds,
      reportDeadlineTime: input.reportDeadlineTime || "",
    };
  
    const validationResult = validateScheduleConfig(validationInput);
    if (!validationResult.isValid) {
      throw new Error(
        `Schedule validation failed: ${validationResult.errors?.map((e) => e.message).join(", ")}`
      );
    }
  
    if (input.userId) {
      const authResult = authorizeScheduleOperation({
        userId: input.userId,
        operationType: "create",
        targetTeamId: input.targetTeamIds[0] || "",
      });
  
      if (!authResult.authorized) {
        throw new Error(`Authorization failed: ${authResult.reason || "Unauthorized"}`);
      }
    }
  
    const saveInput = {
      scheduleId,
      sendTime: input.sendTime,
      targetTeamIds: input.targetTeamIds,
      targetMemberIds: input.targetMemberIds,
      isEnabled: input.isEnabled,
      notificationContent: `Reminder: ${input.scheduleName}`,
      createdAt: now,
      updatedAt: now,
    };
  
    const saveResult = saveSchedule(saveInput);
  
    if (!saveResult.success) {
      throw new Error(`Failed to save schedule: ${saveResult.scheduleId}`);
    }
  
    return {
      scheduleId,
      scheduleName: input.scheduleName,
      sendTime: input.sendTime,
      targetTeamIds: input.targetTeamIds,
      targetMemberIds: input.targetMemberIds,
      isEnabled: input.isEnabled,
      createdAt: now,
      updatedAt: now,
    };
  }
  return { createRemindSchedule };
})();
export const createRemindSchedule = __aivicBundle_1_createRemindSchedule.createRemindSchedule;
/* AIVIC_FUNCTION_BUNDLE_END owner=createRemindSchedule */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateRemindSchedule exports=updateRemindSchedule */
const __aivicBundle_2_updateRemindSchedule = (() => {
  interface UpdateRemindScheduleInput {
    scheduleId: string;
    sendTime?: string;
    targetTeamIds?: string[];
    targetMemberIds?: string[];
    isEnabled?: boolean;
    userId?: string;
  }
  
   function updateRemindSchedule(input: UpdateRemindScheduleInput): RemindSchedule {
    const { scheduleId, sendTime, targetTeamIds, targetMemberIds, isEnabled, userId = "system" } = input;
  
    const authResult = authorizeScheduleOperation({
      userId,
      operationType: "update",
      targetTeamId: targetTeamIds?.[0] ?? "",
      scheduleId,
    });
  
    if (!authResult.authorized) {
      throw new Error(`Authorization failed: ${authResult.reason ?? "Access denied"}`);
    }
  
    const existingSchedule = getExistingScheduleById(scheduleId);
    if (!existingSchedule) {
      throw new Error(`Schedule not found: ${scheduleId}`);
    }
  
    const updatedSendTime = sendTime ?? existingSchedule.sendTime;
    const updatedTeamIds = targetTeamIds ?? existingSchedule.targetTeamIds;
    const updatedMemberIds = targetMemberIds ?? existingSchedule.targetMemberIds;
    const updatedIsEnabled = isEnabled !== undefined ? isEnabled : existingSchedule.isEnabled;
  
    const validationInput: ScheduleConfigInput = {
      sendTime: updatedSendTime,
      selectedTeamIds: updatedTeamIds,
      selectedMemberIds: updatedMemberIds,
      reportDeadlineTime: updatedSendTime,
    };
  
    const validationResult = validateScheduleConfig(validationInput);
    if (!validationResult.isValid) {
      throw new Error(`Validation failed: ${validationResult.errors?.map((e) => e.message).join(", ") ?? "Unknown error"}`);
    }
  
    const now = new Date().toISOString();
  
    const saveInput = {
      scheduleId,
      sendTime: updatedSendTime,
      targetTeamIds: updatedTeamIds,
      targetMemberIds: updatedMemberIds,
      isEnabled: updatedIsEnabled,
      notificationContent: existingSchedule.scheduleName,
      createdAt: existingSchedule.createdAt,
      updatedAt: now,
    };
  
    const saveResult = saveSchedule(saveInput);
  
    if (!saveResult.success) {
      throw new Error(`Failed to save schedule: ${scheduleId}`);
    }
  
    const updatedSchedule: RemindSchedule = {
      scheduleId,
      scheduleName: existingSchedule.scheduleName,
      sendTime: updatedSendTime,
      targetTeamIds: updatedTeamIds,
      targetMemberIds: updatedMemberIds,
      isEnabled: updatedIsEnabled,
      createdAt: existingSchedule.createdAt,
      updatedAt: now,
    };
  
    return updatedSchedule;
  }
  
  interface ScheduleConfigInput {
    sendTime: string;
    selectedTeamIds: string[];
    selectedMemberIds: string[];
    reportDeadlineTime: string;
  }
  
  function getExistingScheduleById(scheduleId: string): RemindSchedule | null {
    const scheduleStore: Record<string, RemindSchedule> = {
      sched_001: {
        scheduleId: "sched_001",
        scheduleName: "Morning Reminder",
        sendTime: "09:00",
        targetTeamIds: ["team1"],
        targetMemberIds: ["user1", "user2"],
        isEnabled: true,
        createdAt: "2024-01-15T08:30:00Z",
        updatedAt: "2024-01-15T08:30:00Z",
      },
      sched_002: {
        scheduleId: "sched_002",
        scheduleName: "Afternoon Check",
        sendTime: "14:00",
        targetTeamIds: ["team2"],
        targetMemberIds: ["user3"],
        isEnabled: true,
        createdAt: "2024-01-14T14:00:00Z",
        updatedAt: "2024-01-14T14:00:00Z",
      },
    };
  
    return scheduleStore[scheduleId] ?? null;
  }
  return { updateRemindSchedule };
})();
export const updateRemindSchedule = __aivicBundle_2_updateRemindSchedule.updateRemindSchedule;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateRemindSchedule */

/* AIVIC_FUNCTION_BUNDLE_START owner=toggleRemindScheduleStatus exports=toggleRemindScheduleStatus */
const __aivicBundle_3_toggleRemindScheduleStatus = (() => {
  interface ToggleScheduleStatusInput {
    scheduleId: string;
    enabled: boolean;
    userId: string;
  }
  
   function toggleRemindScheduleStatus(
    input: ToggleScheduleStatusInput
  ): RemindSchedule {
    const { scheduleId, enabled, userId } = input;
  
    const authResult = authorizeScheduleOperation({
      userId,
      operationType: "toggle",
      targetTeamId: "",
      scheduleId,
    });
  
    if (!authResult.authorized) {
      throw new Error(
        authResult.reason || "User is not authorized to toggle this schedule"
      );
    }
  
    const currentSchedule = loadSchedule({ scheduleId });
  
    const updatedSchedule: RemindSchedule = {
      ...currentSchedule,
      isEnabled: enabled,
      updatedAt: new Date().toISOString(),
    };
  
    saveSchedule({
      scheduleId: updatedSchedule.scheduleId,
      sendTime: updatedSchedule.sendTime,
      targetTeamIds: updatedSchedule.targetTeamIds,
      targetMemberIds: updatedSchedule.targetMemberIds,
      isEnabled: updatedSchedule.isEnabled,
      notificationContent: "",
      createdAt: updatedSchedule.createdAt,
      updatedAt: updatedSchedule.updatedAt,
    });
  
    return updatedSchedule;
  }
  return { toggleRemindScheduleStatus };
})();
export const toggleRemindScheduleStatus = __aivicBundle_3_toggleRemindScheduleStatus.toggleRemindScheduleStatus;
/* AIVIC_FUNCTION_BUNDLE_END owner=toggleRemindScheduleStatus */

/* AIVIC_FUNCTION_BUNDLE_START owner=listRemindSchedules exports=listRemindSchedules */
const __aivicBundle_4_listRemindSchedules = (() => {
  interface ListRemindSchedulesInput {
    userId: string;
    filterStatus?: "active" | "inactive" | "all";
    requestContext?: object;
  }
  
  interface ListRemindSchedulesOutput {
    schedules: RemindScheduleItem[];
    totalCount: number;
    retrievedAt: string;
  }
  
   function listRemindSchedules(
    input: ListRemindSchedulesInput
  ): ListRemindSchedulesOutput {
    const { userId, filterStatus = "all", requestContext = {} } = input;
  
    const authResult = authorizeRemindManagement({
      userId,
      requestContext,
    });
  
    if (!authResult.authorized) {
      return {
        schedules: [],
        totalCount: 0,
        retrievedAt: new Date().toISOString(),
      };
    }
  
    const allScheduleIds = [
      "sched_001",
      "sched_002",
      "sched_003",
      "sched_004",
      "sched_005",
    ];
  
    const loadedSchedules: RemindSchedule[] = [];
    for (const scheduleId of allScheduleIds) {
      try {
        const schedule = loadSchedule({ scheduleId });
        loadedSchedules.push(schedule);
      } catch {
        continue;
      }
    }
  
    const filteredSchedules = loadedSchedules.filter((schedule) => {
      if (filterStatus === "all") return true;
      if (filterStatus === "active") return schedule.isEnabled;
      if (filterStatus === "inactive") return !schedule.isEnabled;
      return true;
    });
  
    const scheduleItems: RemindScheduleItem[] = filteredSchedules.map(
      (schedule) => {
        let timeToDeadline = 0;
        try {
          const deadlineInfo = getDeadlineInfo({
            teamId: schedule.targetTeamIds[0] || "",
            reportType: "morning-report",
            requestedAt: new Date(),
          });
          timeToDeadline = deadlineInfo.remainingMinutes;
        } catch {
          timeToDeadline = 0;
        }
  
        return {
          scheduleId: schedule.scheduleId,
          sendTime: schedule.sendTime,
          targetTeams: schedule.targetTeamIds,
          targetMembers: schedule.targetMemberIds,
          isActive: schedule.isEnabled,
          timeToDeadline,
          createdAt: schedule.createdAt,
          updatedAt: schedule.updatedAt,
        };
      }
    );
  
    return {
      schedules: scheduleItems,
      totalCount: scheduleItems.length,
      retrievedAt: new Date().toISOString(),
    };
  }
  return { listRemindSchedules };
})();
export const listRemindSchedules = __aivicBundle_4_listRemindSchedules.listRemindSchedules;
/* AIVIC_FUNCTION_BUNDLE_END owner=listRemindSchedules */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateScheduleConfig exports=validateScheduleConfig */
const __aivicBundle_5_validateScheduleConfig = (() => {
  interface ValidateScheduleConfigInput {
    sendTime: string;
    selectedTeamIds: string[];
    selectedMemberIds: string[];
    reportDeadlineTime: string;
  }
  
   function validateScheduleConfig(
    input: ValidateScheduleConfigInput
  ): ValidationResult {
    const errors: Array<{ field: string; message: string }> = [];
  
    // Validate sendTime format (HH:MM in 24-hour format)
    if (!isValidTimeFormat(input.sendTime)) {
      errors.push({
        field: "sendTime",
        message:
          "リマインド送信時刻は24時間形式の範囲内である必要があります",
      });
    }
  
    // Validate reportDeadlineTime format
    if (!isValidTimeFormat(input.reportDeadlineTime)) {
      errors.push({
        field: "reportDeadlineTime",
        message: "報告期限は24時間形式の範囲内である必要があります",
      });
    }
  
    // Validate that at least one team or member is selected
    if (
      input.selectedTeamIds.length === 0 &&
      input.selectedMemberIds.length === 0
    ) {
      errors.push({
        field: "selectedTeamIds",
        message: "対象チームまたはメンバーを1件以上選択してください",
      });
    }
  
    // Validate sendTime is before reportDeadlineTime
    if (
      isValidTimeFormat(input.sendTime) &&
      isValidTimeFormat(input.reportDeadlineTime)
    ) {
      const sendTimeMinutes = timeToMinutes(input.sendTime);
      const deadlineTimeMinutes = timeToMinutes(input.reportDeadlineTime);
  
      if (sendTimeMinutes >= deadlineTimeMinutes) {
        errors.push({
          field: "sendTime",
          message: "リマインド送信時刻は報告期限より前である必要があります",
        });
      }
    }
  
    // Validate selected teams exist
    if (input.selectedTeamIds.length > 0) {
      try {
        const availableTeamsOutput = listAvailableTeams({
          userId: "system",
          includeInactive: false,
        });
        const availableTeamIds = availableTeamsOutput.teams.map(
          (team) => team.teamId
        );
  
        const invalidTeamIds = input.selectedTeamIds.filter(
          (teamId) => !availableTeamIds.includes(teamId)
        );
  
        if (invalidTeamIds.length > 0) {
          errors.push({
            field: "selectedTeamIds",
            message: `存在しないチームが含まれています: ${invalidTeamIds.join(", ")}`,
          });
        }
      } catch {
        // If team validation fails, continue with other validations
      }
    }
  
    // Validate selected members belong to their teams
    if (input.selectedMemberIds.length > 0 && input.selectedTeamIds.length > 0) {
      try {
        for (const teamId of input.selectedTeamIds) {
          const teamMembersOutput = listTeamMembers({
            teamId,
            includeInactive: false,
          });
          const validMemberIds = teamMembersOutput.members.map(
            (member) => member.memberId
          );
  
          const invalidMembers = input.selectedMemberIds.filter(
            (memberId) => !validMemberIds.includes(memberId)
          );
  
          if (invalidMembers.length > 0) {
            errors.push({
              field: "selectedMemberIds",
              message: `チーム ${teamId} に属さないメンバーが含まれています`,
            });
            break;
          }
        }
      } catch {
        // If member validation fails, continue with other validations
      }
    }
  
    if (errors.length > 0) {
      return {
        isValid: false,
        errors,
      };
    }
  
    return {
      isValid: true,
    };
  }
  
  function isValidTimeFormat(time: string): boolean {
    const timeRegex = /^([0-1][0-9]|2[0-3]):([0-5][0-9])$/;
    return timeRegex.test(time);
  }
  
  function timeToMinutes(time: string): number {
    const [hours, minutes] = time.split(":").map(Number);
    return hours * 60 + minutes;
  }
  return { validateScheduleConfig };
})();
export const validateScheduleConfig = __aivicBundle_5_validateScheduleConfig.validateScheduleConfig;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateScheduleConfig */
