// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/orchestrator.ts
export { runTx2Imp1Agent } from "../../logic/src/agents/tx-2-imp-1/orchestrator";

/**
 * Tx2Imp1Agent - 日報収集から課題抽出・配信までの自律実行
 * 
 * AIエージェントが日報受信から課題抽出・確認メール配信まで自動で完結し、
 * 部長は配信済みメールを確認するだけで朝会に臨める
 */

/**
 * Tx2Imp1AgentへのInput型定義
 * 日報集約・課題抽出・メール配信処理の入力パラメータ
 */
export interface Tx2Imp1AgentInput {
  /**
   * エージェント実行日時（UTC）
   */
  executionDate: Date;

  /**
   * 対象チームID一覧
   * undefined の場合は全チーム対象
   */
  teamIds?: string[];

  /**
   * 部長への通知メール送信を有効にするか
   */
  managerNotificationEnabled: boolean;
}

/**
 * 優先度付けされた課題情報
 */
export interface PrioritizedIssue {
  /**
   * 課題キーワード
   */
  keyword: string;

  /**
   * 報告頻度
   */
  frequency: number;

  /**
   * 影響を受けたメンバー数
   */
  affectedMemberCount: number;

  /**
   * 優先度スコア（0-100）
   */
  priorityScore: number;

  /**
   * 優先度レベル
   */
  priorityLevel: 'high' | 'medium' | 'low';

  /**
   * UI表示用の色コード
   */
  displayColor: string;
}

/**
 * Tx2Imp1AgentからのOutput型定義
 * 日報集約・課題抽出・メール配信処理の実行結果
 */
export interface Tx2Imp1AgentOutput {
  /**
   * 実行ステータス
   * - success: 全処理が正常に完了
   * - partial_failure: 課題抽出は成功したがメール送信に失敗
   * - failure: 処理が失敗
   */
  executionStatus: 'success' | 'partial_failure' | 'failure';

  /**
   * 抽出された課題の総数
   */
  extractedIssuesCount: number;

  /**
   * 優先度付けされた課題一覧（優先度順）
   */
  prioritizedIssuesList: PrioritizedIssue[];

  /**
   * 部長への確認メール送信成功フラグ
   */
  managerEmailSent: boolean;

  /**
   * 処理実行時刻（UTC）
   */
  processingTimestampUtc: Date;

  /**
   * エラーメッセージ（失敗時のみ）
   */
  errorMessage?: string;
}

/**
 * Tx2Imp1AiClient - AIエージェント実装の境界インターフェース
 * 
 * このインターフェースは runTx2Imp1Agent の第2引数として
 * 構造的に同一である必要があります（Orchestrator boundary）
 */
export interface Tx2Imp1AiClient {
  /**
   * 指定チームの日報提出状況を取得
   */
  getSubmissionStatus?: (teamId: string) => Promise<{
    teamId: string;
    submittedCount: number;
    totalMembers: number;
    submittedAt: Date;
    isOnTime: boolean;
  }>;

  /**
   * 日報から課題を抽出し優先度付けする
   */
  extractAndRankIssuesFromReports?: (
    reports: Array<{
      employeeId: string;
      employeeName: string;
      yesterday: string;
      today: string;
      issue: string;
      submittedAt: string;
    }>
  ) => Promise<PrioritizedIssue[]>;

  /**
   * 部長向け確認メールを生成・送信
   */
  generateAndSendManagerConfirmationEmail?: (
    issues: PrioritizedIssue[],
    executionDate: Date
  ) => Promise<{
    emailSent: boolean;
    emailId: string;
    sentAt: Date;
  }>;

  /**
   * 日報データベースから当日の日報を集約
   */
  aggregateDailyReportsFromDatabase?: () => Promise<{
    submittedReportCount: number;
    reportDataList: Array<{
      employeeId: string;
      employeeName: string;
      yesterday: string;
      today: string;
      issue: string;
      submittedAt: string;
    }>;
    allTeamMembers: Array<{
      employeeId: string;
      employeeName: string;
    }>;
  }>;

  /**
   * 日報から課題キーワードを抽出
   */
  extractIssueKeywordsFromReports?: () => Promise<{
    extractedKeywords: Array<{
      keyword: string;
      frequency: number;
      rank: number;
    }>;
  }>;

  /**
   * 課題の優先度スコアを計算
   */
  calculateIssuePriorityScores?: (
    keywords: Array<{
      keyword: string;
      frequency: number;
      rank: number;
    }>
  ) => Promise<{
    prioritizedIssues: PrioritizedIssue[];
  }>;

  /**
   * 日報を取得
   */
  fetchDailyReportsForTeams?: (teamIds?: string[]) => Promise<
    Array<{
      employeeId: string;
      employeeName: string;
      yesterday: string;
      today: string;
      issue: string;
      submittedAt: string;
    }>
  >;

  /**
   * 未提出メンバーを特定
   */
  identifyUnsubmittedMembers?: (teamIds?: string[]) => Promise<
    Array<{
      employeeId: string;
      employeeName: string;
    }>
  >;

  /**
   * 確認メールをフォーマットして送信
   */
  formatAndSendConfirmationEmail?: (
    issues: PrioritizedIssue[],
    executionDate: Date
  ) => Promise<{
    emailSent: boolean;
    sentAt: Date;
  }>;

  /**
   * 処理イベントをログに記録
   */
  logProcessingEvent?: (
    eventType: string,
    details: Record<string, unknown>
  ) => Promise<void>;
}
