// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-06.ts

/**
 * Action 06 Prompt Module for tx-2-imp-1 Agent
 * 
 * Responsible for generating the prompt for Action 6:
 * "部長へ完成通知を送信" (Send completion notification to department head)
 * 
 * This action completes the autonomous workflow by notifying the department head
 * that the email with extracted issues has been generated and is ready for review.
 */

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06PromptInput {
  departmentHeadEmail: string;
  departmentHeadName: string;
  emailGenerationTimestamp: string;
  issueCount: number;
  priorityBreakdown: {
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
  reportGenerationStatus: "success" | "partial" | "failed";
  reportUrl?: string;
  notificationDeliveryMethod: "email" | "slack" | "teams" | "system";
  systemName: string;
}

export interface Action06PromptOutput {
  notificationTitle: string;
  notificationBody: string;
  callToAction: string;
  urgencyLevel: "immediate" | "high" | "normal" | "low";
  deliveryInstructions: {
    method: string;
    recipient: string;
    timing: string;
  };
}

export function buildAction06Prompt(input: Action06PromptInput): string {
  const priorityText = `
Critical: ${input.priorityBreakdown.critical}件
High: ${input.priorityBreakdown.high}件
Medium: ${input.priorityBreakdown.medium}件
Low: ${input.priorityBreakdown.low}件
`;

  const statusIndicator =
    input.reportGenerationStatus === "success"
      ? "✓ 正常に完了"
      : input.reportGenerationStatus === "partial"
        ? "⚠ 部分的に完了"
        : "✗ 失敗";

  const reportLinkSection = input.reportUrl
    ? `\n\nレポートURL: ${input.reportUrl}`
    : "";

  const prompt = `
あなたは朝会報告管理システムの自動通知エージェントです。

【タスク】
部長（${input.departmentHeadName}）に対して、日報から抽出した課題の確認メール生成が完了したことを通知してください。

【生成完了情報】
- 生成完了時刻: ${input.emailGenerationTimestamp}
- 抽出課題総数: ${input.issueCount}件
- 優先度別内訳:
${priorityText}
- 生成ステータス: ${statusIndicator}
${reportLinkSection}

【通知要件】
1. 部長が朝会前に確認できるよう、簡潔で要点を押さえた通知を作成してください
2. 優先度が高い課題がある場合は、その旨を強調してください
3. 通知方法は${input.notificationDeliveryMethod}を使用してください
4. 部長が次のアクション（メール確認、朝会資料の最終確認）を明確に理解できるようにしてください

【出力形式】
以下のJSON形式で返してください:
{
  "notificationTitle": "通知のタイトル（20文字以内）",
  "notificationBody": "通知本文（200文字以内、改行含む）",
  "callToAction": "次のアクション指示（50文字以内）",
  "urgencyLevel": "immediate|high|normal|low",
  "deliveryInstructions": {
    "method": "${input.notificationDeliveryMethod}",
    "recipient": "${input.departmentHeadEmail}",
    "timing": "通知送信のタイミング指示"
  }
}

【制約】
- 通知は客観的で、感情的な表現は避けてください
- 部長の判断を促すような表現は避けてください
- システム名は「${input.systemName}」として参照してください
`;

  return prompt;
}
