// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-10-imp-1/prompts/action-06.ts

/**
 * Action 06: 部長へ完成通知を送信
 * 
 * tx-10-imp-1 エージェントの第6アクション
 * 優先度順に整理した朝会資料が完成したことを部長に通知する
 */

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06Context {
  reportId: string;
  reportTitle: string;
  reportUrl: string;
  completionTime: string;
  prioritizedIssuesCount: number;
  unsubmittedMembersCount: number;
  departmentName: string;
}

export interface Action06PromptResult {
  notificationMessage: string;
  recipientEmail: string;
  subject: string;
  priority: "high" | "normal" | "low";
  includeAttachments: boolean;
  scheduledSendTime?: string;
}

export function buildAction06Prompt(context: Action06Context): string {
  const {
    reportId,
    reportTitle,
    reportUrl,
    completionTime,
    prioritizedIssuesCount,
    unsubmittedMembersCount,
    departmentName,
  } = context;

  return `# Action 06: 部長へ完成通知を送信

## 目的
優先度順に整理した朝会資料が完成したことを部長に通知し、確認・承認を促す

## 入力情報
- レポートID: ${reportId}
- レポートタイトル: ${reportTitle}
- レポートURL: ${reportUrl}
- 完成時刻: ${completionTime}
- 優先度付け済み課題数: ${prioritizedIssuesCount}
- 未提出メンバー数: ${unsubmittedMembersCount}
- 部門名: ${departmentName}

## 実行内容
1. 朝会資料の完成を部長に通知するメール本文を生成する
2. 通知メールの件名を決定する
3. 送信優先度を判定する（未提出者が多い場合は高優先度）
4. 添付ファイルの必要性を判定する
5. 送信スケジュールを決定する（即座送信 or 予約送信）

## 出力形式
以下の JSON 形式で通知内容を返す：
{
  "notificationMessage": "部長宛の通知メール本文",
  "recipientEmail": "部長のメールアドレス",
  "subject": "メール件名",
  "priority": "high|normal|low",
  "includeAttachments": true|false,
  "scheduledSendTime": "2024-01-15T08:30:00Z" (オプション)
}

## 判定ルール
- 未提出メンバーが5名以上の場合: 優先度 high
- 優先度付け済み課題が10件以上の場合: 優先度 high
- それ以外: 優先度 normal
- 添付ファイルは常に false（URL参照で十分）
- 送信時刻は即座（scheduledSendTime は省略）

## 注意事項
- 部長の確認時間を確保するため、朝会開始の15分前までに送信する
- 通知メールには必ずレポートURLを含める
- 未提出メンバーが存在する場合は、その旨を明記する
- 重大課題が含まれる場合は、その旨を強調する`;
}
