// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-10-imp-1/prompts/action-03.ts

/**
 * src/agents/tx-10-imp-1/prompts/action-03.ts
 * 
 * Action 3: 初回報告データを収集・分析し、提出状況と内容品質を評価する
 * 
 * Contract: tx_10_imp_1
 * Orchestrator: src/agents/tx-10-imp-1/orchestrator.ts
 * Orchestrator function: runTx10Imp1Agent
 */

export const ACTION_03_PROMPT_VERSION = "1.0.0";

export interface InitialReportAnalysisContext {
  deploymentPhase: "pre-deployment" | "post-deployment" | "stabilization";
  targetDepartmentId: string;
  targetDepartmentName: string;
  collectionStartDate: string;
  collectionEndDate: string;
  totalMembersExpected: number;
  reportSystemUrl?: string;
}

export interface ReportSubmissionStatus {
  memberId: string;
  memberName: string;
  submitted: boolean;
  submissionTimestamp?: string;
  isLate: boolean;
}

export interface ReportContentQuality {
  memberId: string;
  memberName: string;
  completenessScore: number;
  clarityScore: number;
  structureScore: number;
  overallQualityScore: number;
  issues: string[];
  strengths: string[];
}

export interface InitialReportAnalysisResult {
  analysisTimestamp: string;
  collectionPeriod: {
    startDate: string;
    endDate: string;
  };
  submissionStatistics: {
    totalExpected: number;
    totalSubmitted: number;
    submissionRate: number;
    lateSubmissions: number;
    nonSubmissions: number;
  };
  submissionDetails: ReportSubmissionStatus[];
  contentQualityAnalysis: ReportContentQuality[];
  memberProficiencyAssessment: {
    memberId: string;
    memberName: string;
    proficiencyLevel: "beginner" | "intermediate" | "advanced";
    identifiedChallenges: string[];
    recommendedSupport: string[];
  }[];
  aggregatedIssues: {
    category: string;
    frequency: number;
    severity: "low" | "medium" | "high";
    affectedMembers: string[];
  }[];
  feedbackRecommendations: {
    targetMemberId: string;
    targetMemberName: string;
    feedbackType: "encouragement" | "guidance" | "correction" | "escalation";
    feedbackContent: string;
    priority: "low" | "medium" | "high";
  }[];
  overallAssessment: {
    adoptionReadiness: number;
    dataQualityLevel: "poor" | "fair" | "good" | "excellent";
    recommendedNextSteps: string[];
    escalationRequired: boolean;
    escalationReason?: string;
  };
}

export interface Action03PromptInput {
  context: InitialReportAnalysisContext;
  submissionData: ReportSubmissionStatus[];
  reportContentSamples: {
    memberId: string;
    memberName: string;
    reportContent: string;
    submissionTime: string;
  }[];
  historicalQualityBaseline?: {
    expectedCompletenessScore: number;
    expectedClarityScore: number;
    expectedStructureScore: number;
  };
  organizationContext?: {
    departmentType: string;
    teamSize: number;
    industryType: string;
    previousSystemExperience: boolean;
  };
}

export interface Action03PromptOutput {
  analysisResult: InitialReportAnalysisResult;
  promptUsageMetrics?: {
    tokensUsed: number;
    processingTimeMs: number;
  };
}

export function buildAction03Prompt(input: Action03PromptInput): string {
  const {
    context,
    submissionData,
    reportContentSamples,
    historicalQualityBaseline,
    organizationContext,
  } = input;

  const submissionRate = submissionData.length > 0
    ? (submissionData.filter((s) => s.submitted).length / context.totalMembersExpected) * 100
    : 0;

  const lateCount = submissionData.filter((s) => s.isLate).length;

  const baselineInfo = historicalQualityBaseline
    ? `
Historical Quality Baseline:
- Expected Completeness Score: ${historicalQualityBaseline.expectedCompletenessScore}
- Expected Clarity Score: ${historicalQualityBaseline.expectedClarityScore}
- Expected Structure Score: ${historicalQualityBaseline.expectedStructureScore}
`
    : "";

  const orgContextInfo = organizationContext
    ? `
Organization Context:
- Department Type: ${organizationContext.departmentType}
- Team Size: ${organizationContext.teamSize}
- Industry Type: ${organizationContext.industryType}
- Previous System Experience: ${organizationContext.previousSystemExperience ? "Yes" : "No"}
`
    : "";

  const reportSamplesText = reportContentSamples
    .map(
      (sample) => `
Member: ${sample.memberName} (ID: ${sample.memberId})
Submission Time: ${sample.submissionTime}
Report Content:
${sample.reportContent}
---
`,
    )
    .join("\n");

  const submissionDetailsText = submissionData
    .map(
      (status) => `
- ${status.memberName} (ID: ${status.memberId}): ${status.submitted ? "Submitted" : "Not Submitted"}${
        status.submitted ? ` at ${status.submissionTimestamp}` : ""
      }${status.isLate ? " [LATE]" : ""}
`,
    )
    .join("\n");

  return `You are an AI agent responsible for analyzing initial report data from a newly deployed morning report management system.

DEPLOYMENT CONTEXT:
- Target Department: ${context.targetDepartmentName} (ID: ${context.targetDepartmentId})
- Deployment Phase: ${context.deploymentPhase}
- Collection Period: ${context.collectionStartDate} to ${context.collectionEndDate}
- Total Expected Members: ${context.totalMembersExpected}
- System URL: ${context.reportSystemUrl || "Not provided"}

SUBMISSION STATISTICS:
- Total Submitted: ${submissionData.filter((s) => s.submitted).length}
- Total Not Submitted: ${submissionData.filter((s) => !s.submitted).length}
- Submission Rate: ${submissionRate.toFixed(2)}%
- Late Submissions: ${lateCount}

SUBMISSION DETAILS:
${submissionDetailsText}

REPORT CONTENT SAMPLES FOR QUALITY ANALYSIS:
${reportSamplesText}

${baselineInfo}

${orgContextInfo}

ANALYSIS TASKS:

1. SUBMISSION STATUS ANALYSIS:
   - Evaluate submission rate against expected targets
   - Identify patterns in late submissions
   - Assess adoption readiness based on submission behavior

2. CONTENT QUALITY EVALUATION:
   For each report sample provided, evaluate:
   - Completeness Score (0-100): How complete is the report structure?
   - Clarity Score (0-100): How clear and understandable is the content?
   - Structure Score (0-100): How well does it follow the expected format?
   - Overall Quality Score (0-100): Average of the three scores
   - Identify specific issues and strengths

3. MEMBER PROFICIENCY ASSESSMENT:
   - Categorize each member's proficiency level (beginner/intermediate/advanced)
   - Identify specific challenges they face
   - Recommend targeted support for each member

4. AGGREGATED ISSUE IDENTIFICATION:
   - Extract common issues across all reports
   - Categorize issues by type
   - Assess frequency and severity
   - Identify which members are affected

5. FEEDBACK RECOMMENDATIONS:
   - Generate specific, actionable feedback for each member
   - Categorize feedback type (encouragement/guidance/correction/escalation)
   - Prioritize feedback by importance
   - Ensure feedback is constructive and supportive

6. OVERALL ASSESSMENT:
   - Calculate adoption readiness score (0-100)
   - Determine data quality level (poor/fair/good/excellent)
   - Recommend next steps for stabilization
   - Identify any escalation needs

IMPORTANT GUIDELINES:
- Be constructive and supportive in feedback
- Consider that this is the initial deployment phase
- Account for learning curve expectations
- Identify both strengths and areas for improvement
- Provide actionable recommendations
- Flag any critical issues requiring immediate attention
- Consider team dynamics and peer learning opportunities

OUTPUT FORMAT:
Provide a comprehensive analysis in JSON format with the following structure:
{
  "analysisTimestamp": "ISO 8601 timestamp",
  "collectionPeriod": {
    "startDate": "date",
    "endDate": "date"
  },
  "submissionStatistics": {
    "totalExpected": number,
    "totalSubmitted": number,
    "submissionRate": number (0-100),
    "lateSubmissions": number,
    "nonSubmissions": number
  },
  "submissionDetails": [array of submission status objects],
  "contentQualityAnalysis": [array of quality analysis objects],
  "memberProficiencyAssessment": [array of proficiency assessment objects],
  "aggregatedIssues": [array of aggregated issue objects],
  "feedbackRecommendations": [array of feedback recommendation objects],
  "overallAssessment": {
    "adoptionReadiness": number (0-100),
    "dataQualityLevel": "poor|fair|good|excellent",
    "recommendedNextSteps": [array of strings],
    "escalationRequired": boolean,
    "escalationReason": "string or null"
  }
}

Ensure all analysis is data-driven, fair, and constructive.`;
}
